### ISSUE TITLE
Creating ADFS SAML2 Security Integration fails if saml2_sign_request is set to true

### ISSUE THREAD

**Issue by BoAustin** [Snowflake-Labs/terraform-provider-snowflake#1004]
**Provider Version**

0.33.1

**Terraform Version**

Terraform v1.1.9
on darwin_amd64

**Describe the bug**

When creating a snowflake_saml_integration resource if you specify the boolean parameter saml2_sign_request = true you get the follow error while applying changes:

```
╷
│ Error: Plugin did not respond
│ 
│   with module.snowflake-account.module.snowflake-sso[0].snowflake_saml_integration.saml_integration,
│   on terraform-snowflake-sso/main.tf line 14, in resource "snowflake_saml_integration" "saml_integration":
│   14: resource "snowflake_saml_integration" "saml_integration" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-snowflake_v0.33.1 plugin:

panic: interface conversion: interface {} is bool, not string

goroutine 35 [running]:
github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources.CreateSAMLIntegration(0x0, {0x119faa0, 0xc00012b380})
        github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources/saml_integration.go:188 +0xb99
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1058360, {0x13c8f98, 0xc00036cb40}, 0x2, {0x119faa0, 0xc00012b380})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:329 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0004b30a0, {0x13c8f98, 0xc00036cb40}, 0xc000098f70, 0xc0000e1280, {0x119faa0, 0xc00012b380})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:467 +0x871
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0001260a8, {0x13c8f98, 0xc00036cb40}, 0xc00071b3b0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:977 +0xd8a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0003fc280, {0x13c9040, 0xc000722ea0}, 0xc000566e00)
        github.com/hashicorp/terraform-plugin-go@v0.7.1/tfprotov5/tf5server/server.go:812 +0x5eb
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x116f0e0, 0xc0003fc280}, {0x13c9040, 0xc000722ea0}, 0xc00011b140, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.7.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00013e700, {0x13dc0c8, 0xc00047e4e0}, 0xc00072a240, 0xc00047ccf0, 0x1b81ec0, 0x0)
        google.golang.org/grpc@v1.44.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc00013e700, {0x13dc0c8, 0xc00047e4e0}, 0xc00072a240, 0x0)
        google.golang.org/grpc@v1.44.0/server.go:1616 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.44.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.44.0/server.go:919 +0x294

Error: The terraform-provider-snowflake_v0.33.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Expected behavior**

Changes apply successfully.

**Code samples and commands**

```
resource "snowflake_saml_integration" "saml_integration" {
  provider        = snowflake.accountadmin
  name            = "SAML_IDENTITY_PROVIDER"
  saml2_issuer    = "https://sts.windows.net/xxx/"
  saml2_provider  = "ADFS"
  saml2_sso_url   = https://login.microsoftonline.com/xxx/saml2
  saml2_x509_cert = "<cert>"
  # Optional
  saml2_sign_request = true
}
```

**Additional context**

A workaround is to create the resource without the saml2_sign_request then set it to true and updating the resource will succeed. The problem appears to be with creating the resource with the saml2_sign_request = true that throws the error.

**Comment by sfc-gh-asawicki** [comment]
We are closing this issue as part of a cleanup described in [announcement](https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/2755). If you believe that the issue is still valid in v0.89.0, please open a new ticket.
