### ISSUE TITLE
Plugin did not respond: error: The terraform-provider-snowflake_v0.33.1 plugin crashed!

### ISSUE THREAD

**Issue by kbroughton** [Snowflake-Labs/terraform-provider-snowflake#1076]
**Provider Version**
terraform-provider-snowflake_v0.33.1

**Terraform Version**
$ terraform -v
Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/chanzuckerberg/snowflake v0.33.1
+ provider registry.terraform.io/hashicorp/tls v3.3.0

** Remote
Using TFC as remote

**Describe the bug**
```
Error: The terraform-provider-snowflake_v0.33.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

╷
│ Error: Plugin did not respond
│
│   with snowflake_role_grants.ur_to_br_grants["Example:User"],
│   on main.tf line 317, in resource "snowflake_role_grants" "ur_to_br_grants":
│  317: resource snowflake_role_grants "ur_to_br_grants" {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details
```

It appears there is a provider-side issue.

**Expected behavior**

* terraform plan should run without errors
* better error messaging. If this is related to the provider upgrade (which also forces tf version upgrade)
   the error should direct the user to upgrade.

**Code samples and commands**

terraform plan

```
terraform {
  backend "remote" {
    organization = "example-security"

    workspaces {
      name = "security_snowflake"
    }
  }
}


terraform {
  required_providers {
    snowflake = {
      source  = "chanzuckerberg/snowflake"
      version = "0.33.1"
    }
  }
}

provider "snowflake" {
  alias           = "sys_admin"
  role            = "SYSADMIN"
  account         = "PFXXXXXX"
  host            = "example.snowflakecomputing.com"
  username        = "EXAMPLE_SNOW"
  private_key     = var.EXAMPLE_RSA_PRIVATE_KEY

}


data "snowflake_tables" "panther_logs" {
    provider    = snowflake.sys_admin
    database = "PANTHER_LOGS"
    schema   = "PUBLIC"
}

```

**Additional context**
I ran this about 2 weeks ago. Made very minimal changes to main.tf.
Now I cannot do anything with the snowflake provider.

**Stack Trace**

```
Stack trace from the terraform-provider-snowflake_v0.33.1 plugin:

panic: time: missing Location in call to Time.In

goroutine 69 [running]:
time.Time.In(...)
	time/time.go:1106
github.com/snowflakedb/gosnowflake.stringToValue(0xc000889cb0, {{0xc000586160, 0xa}, 0x0, 0x0, {0xc000586170, 0xd}, 0x0, 0x3, 0x1}, ...)
	github.com/snowflakedb/gosnowflake@v1.6.7/converter.go:227 +0xe06
github.com/snowflakedb/gosnowflake.(*snowflakeRows).Next(0xc0003c68a0, {0xc000889cb0, 0x9, 0xd})
	github.com/snowflakedb/gosnowflake@v1.6.7/rows.go:173 +0x4b6
github.com/luna-duclos/instrumentedsql.wrappedRows.Next({{{0x13a5940, 0xc0003ccf70}, {0x13a59a0, 0x1bc3598}, 0x0, 0x0}, {0x13c8fd0, 0xc00004e070}, {0x13b5658, 0xc0003c68a0}}, ...)
	github.com/luna-duclos/instrumentedsql@v1.1.3/rows.go:52 +0x1e2
database/sql.(*Rows).nextLocked(0xc00005c700)
	database/sql/sql.go:2967 +0x111
database/sql.(*Rows).Next.func1()
	database/sql/sql.go:2945 +0x2f
database/sql.withLock({0x13b3ff8, 0xc00005c730}, 0xc0009ff408)
	database/sql/sql.go:3396 +0x8c
database/sql.(*Rows).Next(0xc00005c700)
	database/sql/sql.go:2944 +0x6f
github.com/jmoiron/sqlx.scanAll({0x13ced18, 0xc00054c870}, {0xfcefa0, 0xc0002df290}, 0x1)
	github.com/jmoiron/sqlx@v1.3.4/sqlx.go:950 +0x5a7
github.com/jmoiron/sqlx.StructScan(...)
	github.com/jmoiron/sqlx@v1.3.4/sqlx.go:1001
github.com/chanzuckerberg/terraform-provider-snowflake/pkg/snowflake.ListDatabases(0x203000)
	github.com/chanzuckerberg/terraform-provider-snowflake/pkg/snowflake/database.go:106 +0xe5
github.com/chanzuckerberg/terraform-provider-snowflake/pkg/datasources.ReadDatabases(0x68, {0x119faa0, 0xc0002e61a0})
	github.com/chanzuckerberg/terraform-provider-snowflake/pkg/datasources/databases.go:73 +0xc5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x11b4cb5, {0x13c8f98, 0xc00012a4c0}, 0xc000116f00, {0x119faa0, 0xc0002e61a0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:346 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc00079c7e0, {0x13c8f98, 0xc00012a4c0}, 0xc0005c0a00, {0x119faa0, 0xc0002e61a0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:569 +0xf7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc0005b8078, {0x13c8f98, 0xc00012a4c0}, 0xc0006367e0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:1133 +0x3a8
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc000430320, {0x13c9040, 0xc0001163f0}, 0xc0006301e0)
	github.com/hashicorp/terraform-plugin-go@v0.7.1/tfprotov5/tf5server/server.go:657 +0x50b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0x116f0e0, 0xc000430320}, {0x13c9040, 0xc0001163f0}, 0xc00061e120, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.7.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:421 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004a4700, {0x13dc0c8, 0xc0001031e0}, 0xc0000d6360, 0xc000503ce0, 0x1b81ef0, 0x0)
	google.golang.org/grpc@v1.44.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0004a4700, {0x13dc0c8, 0xc0001031e0}, 0xc0000d6360, 0x0)
	google.golang.org/grpc@v1.44.0/server.go:1616 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.44.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.44.0/server.go:919 +0x294
panic: time: missing Location in call to Time.In

goroutine 97 [running]:
time.Time.In(...)
	time/time.go:1106
github.com/snowflakedb/gosnowflake.stringToValue(0xc000347310, {{0xc000acbcd0, 0xa}, 0x0, 0x0, {0xc000acbce0, 0xd}, 0x0, 0x3, 0x1}, ...)
	github.com/snowflakedb/gosnowflake@v1.6.7/converter.go:227 +0xe06
github.com/snowflakedb/gosnowflake.(*snowflakeRows).Next(0xc00025fe60, {0xc000347310, 0x5, 0xd})
	github.com/snowflakedb/gosnowflake@v1.6.7/rows.go:173 +0x4b6
github.com/luna-duclos/instrumentedsql.wrappedRows.Next({{{0x13a5940, 0xc0003ccf70}, {0x13a59a0, 0x1bc3598}, 0x0, 0x0}, {0x13c8fd0, 0xc00004e070}, {0x13b5658, 0xc00025fe60}}, ...)
	github.com/luna-duclos/instrumentedsql@v1.1.3/rows.go:52 +0x1e2
database/sql.(*Rows).nextLocked(0xc000a39380)
	database/sql/sql.go:2967 +0x111
database/sql.(*Rows).Next.func1()
	database/sql/sql.go:2945 +0x2f
database/sql.withLock({0x13b3ff8, 0xc000a393b0}, 0xc000171570)
	database/sql/sql.go:3396 +0x8c
database/sql.(*Rows).Next(0xc000a39380)
	database/sql/sql.go:2944 +0x6f
github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources.readGrants(0xc00045b5f0, {0xc00044e4c0, 0x1e})
	github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources/role_grants.go:181 +0x21e
github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources.ReadRoleGrants(0xc0004e3080, {0x119faa0, 0xc00045b5f0})
	github.com/chanzuckerberg/terraform-provider-snowflake/pkg/resources/role_grants.go:130 +0x2d2
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x11b4cb5, {0x13c8f98, 0xc00038bd00}, 0x24, {0x119faa0, 0xc00045b5f0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:346 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0002f61c0, {0x13c8f98, 0xc00038bd00}, 0xc0000c1520, {0x119faa0, 0xc00045b5f0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:635 +0x35b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00000c438, {0x13c8f98, 0xc00038bd00}, 0xc000536d40)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:576 +0x534
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc000418320, {0x13c9040, 0xc00036a750}, 0xc000501740)
	github.com/hashicorp/terraform-plugin-go@v0.7.1/tfprotov5/tf5server/server.go:746 +0x537
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x116f0e0, 0xc000418320}, {0x13c9040, 0xc00036a750}, 0xc0005016e0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.7.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004a2a80, {0x13dc0c8, 0xc00050cd00}, 0xc00068d0e0, 0xc0004a4ae0, 0x1b81e90, 0x0)
	google.golang.org/grpc@v1.44.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0004a2a80, {0x13dc0c8, 0xc00050cd00}, 0xc00068d0e0, 0x0)
	google.golang.org/grpc@v1.44.0/server.go:1616 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.44.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.44.0/server.go:919 +0x294

Error: The terraform-provider-snowflake_v0.33.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

Operation failed: failed running terraform plan (exit 1)
```

**Comment by kbroughton** [comment]
I initially tried to make the changes one at a time.  We didn't have required_version for terraform. It was 1.0.11.
We were at 0.33.1. I presume we don't need to roll back to 0.32.0?
First we only changed chanzuckerberg -> Snowflake-Labs and ran
```
terraform state replace-provider chanzuckerberg/snowflake Snowflake-Labs/snowflake
```

Then I added the required_version and updated the version to 1.1.8 in TFC.
Finally I reverted 0.33.1 to 0.32.0. In all cases the provider panicked with similar errors.
My current testing is:

```
terraform {
  required_version = ">= 1.1.7"

  required_providers {
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "0.33.1"
    }
  }
```


Error: The terraform-provider-snowflake_v0.32.0 plugin crashed!

**Comment by sfc-gh-dszmolka** [comment]
bumping provider to 0.36.0 apparently also bumps the bundled Snowflake Go driver version to 1.6.9 (github.com/snowflakedb/gosnowflake v1.6.9 ) which has the fix for the underlying issue (https://github.com/snowflakedb/gosnowflake/issues/555)
