### ISSUE TITLE
The terraform-provider-snowflake_v0.45.0 plugin crashed - snowflake_procedure 

### ISSUE THREAD

**Issue by satar** [Snowflake-Labs/terraform-provider-snowflake#1321]
I've been provisioning several resources successfully, to include a stage, stream, and table. However, when I added a "snowflake_procedure" terraform crashed on me:
```
Terraform will perform the following actions:

  # module.incidents-to-s3.snowflake_procedure.no_params will be created
  + resource "snowflake_procedure" "no_params" {
      + comment             = "user-defined procedure"
      + database            = "RESPONSE_ANALYTICS"
      + execute_as          = "OWNER"
      + id                  = (known after apply)
      + language            = "JAVASCRIPT"
      + name                = "INCIDENTS_S3_EXPORT_TF"
      + null_input_behavior = "CALLED ON NULL INPUT"
      + return_behavior     = "VOLATILE"
      + return_type         = "VARIANT NOT NULL"
      + schema              = "ANALYTICS"
      + statement           = <<-EOT
            var stmt = snowflake.createStatement({
                sqlText: 'CALL INCIDENTS_S3_EXPORT_TF(:1, :2, :3)',
                binds: [null, null, 0]
            });
            
            var result = stmt.execute();
            result.next();
            return result.getColumnValue(1);
        EOT
    }

Plan: 1 to add, 0 to change, 0 to destroy.
module.incidents-to-s3.snowflake_procedure.no_params: Creating...
‚ï∑
‚îÇ Error: Plugin did not respond
‚îÇ 
‚îÇ   with module.incidents-to-s3.snowflake_procedure.no_params,
‚îÇ   on ../../../../../analytics-terraform-modules/snowflake-evbg-incidents/sf-procedure.tf line 1, in resource "snowflake_procedure" "no_params":
‚îÇ    1: resource "snowflake_procedure" "no_params" {
‚îÇ 
‚îÇ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
‚ïµ

Stack trace from the terraform-provider-snowflake_v0.45.0 plugin:

panic: runtime error: index out of range [1] with length 0

goroutine 85 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.ReadProcedure(0xc0007d3f80, {0x1e5b320?, 0xc00088b380})
        github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/procedure.go:274 +0x11c9
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.CreateProcedure(0x0?, {0x1e5b320?, 0xc00088b380})
        github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/procedure.go:200 +0x5e5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x20ae680?, {0x20ae680?, 0xc000108990?}, 0xd?, {0x1e5b320?, 0xc00088b380?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.21.0/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0004316c0, {0x20ae680, 0xc000108990}, 0xc00081e0d0, 0xc0007d3c00, {0x1e5b320, 0xc00088b380})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.21.0/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00036a0f0, {0x20ae680?, 0xc000108870?}, 0xc00039e280)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.21.0/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00053c1e0, {0x20ae680?, 0xc000554090?}, 0xc000498070)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1e27f60?, 0xc00053c1e0}, {0x20ae680, 0xc000554090}, 0xc000498000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00017e000, {0x20b40c0, 0xc0005829c0}, 0xc0007adb00, 0xc000283ad0, 0x2816420, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1295 +0xb2b
google.golang.org/grpc.(*Server).handleStream(0xc00017e000, {0x20b40c0, 0xc0005829c0}, 0xc0007adb00, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1636 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-snowflake_v0.45.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```
I am attempting to create this in a tf file within a module:
snowflake-incidents/sf-procedure.tf:
```
locals {
  source_database = "RESPONSE_ANALYTICS"
  source_schema   = "ANALYTICS"

  sf_role = "RESPONSEANALYTICS_RL"
}

resource "snowflake_procedure" "no_params" {
  name     = "INCIDENTS_S3_EXPORT_TF"
  database = local.source_database
  schema   = local.source_schema
  language = "JAVASCRIPT"
  #  comment             = ""
  return_type = "VARIANT NOT NULL"
  execute_as  = "OWNER"
  # This is the default behavior
  null_input_behavior = "CALLED ON NULL INPUT"
  statement           = <<EOT
var stmt = snowflake.createStatement({
    sqlText: 'CALL INCIDENTS_S3_EXPORT_TF(:1, :2, :3)',
    binds: [null, null, 0]
});

var result = stmt.execute();
result.next();
return result.getColumnValue(1);
EOT
}
```
main.tf
```
module "incidents-to-s3" {
  source      = "../../../../../modules/snowflake-evbg-incidents"
  environment = local.environment
}
```

Note: The procedure does get created in snowflake; however, obviously the crash is not a good thing.

**Comment by satar** [comment]
I noticed that I was not on the very latest version and updating to v0.48.0 this problem went away 🎉
