### ISSUE TITLE
Exception while generating plan, The plugin encountered an error, and failed to respond to the │ plugin.(*GRPCProvider).ReadResource call

### ISSUE THREAD

**Issue by AHirbawi** [Snowflake-Labs/terraform-provider-snowflake#1393]
**Provider Version**
v0.52.0

**Terraform Version**
v1.2.5

**Describe the bug**

After running terraform -out plan.out, i started to receive the below exception, it used to be working fine.
Im using macOS v12.6

Error: Plugin did not respond
│ 
│   with NAME,
│   on auth/functions.tf line 1, in resource "snowflake_function" "NAME":
│    1: resource snowflake_function NAME {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.

Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-snowflake_v0.52.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1b9fe76]

goroutine 91 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.ReadFunction(0xc000ab1a00, {0x1e78f80?, 0xc000aa8dd0})
	github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/function.go:281 +0x3b6
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x20d27a0?, {0x20d27a0?, 0xc000ab5140?}, 0xd?, {0x1e78f80?, 0xc000aa8dd0?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:712 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000741b20, {0x20d27a0, 0xc000ab5140}, 0xc0006ca0d0, {0x1e78f80, 0xc000aa8dd0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000451e18, {0x20d27a0?, 0xc000ab5020?}, 0xc0004b7100)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:613 +0x4a5
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0007a40a0, {0x20d27a0?, 0xc000ab4a50?}, 0xc00077fd40)
	github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:748 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x1e461c0?, 0xc0007a40a0}, {0x20d27a0, 0xc000ab4a50}, 0xc0002c57a0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000401e0, {0x20d81e0, 0xc000503040}, 0xc000a207e0, 0xc00078f710, 0x2843450, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1295 +0xb2b
google.golang.org/grpc.(*Server).handleStream(0xc0000401e0, {0x20d81e0, 0xc000503040}, 0xc000a207e0, 0x0)
	google.golang.org/grpc@v1.48.0/server.go:1636 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-snowflake_v0.52.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Expected behavior**
The plan to be created successfully and be able to deploy it.

**Code samples and commands**

Please add code examples and commands that were run to cause the problem.

**Additional context**

**Comment by sfc-gh-asawicki** [comment]
Hey @AHirbawi.

In v0.100.0, we have introduced new function resources. They differ significantly from v0.52 version. Please use the newest resources and let us know if they work for you.

**Comment by sfc-gh-asawicki** [comment]
Closing due to inactivity. Please create a new issue if the problem persists in the newest provider version.
