### ISSUE TITLE
Plugin crashes when existing `snowflake_resource_monitor` updated from deprecated `triggers` attributes

### ISSUE THREAD

**Issue by joshuaghezzi** [Snowflake-Labs/terraform-provider-snowflake#1680]
**Provider Version**

`v0.60.0`

**Terraform Version**

`v1.3.6`

**Describe the bug**

The plugin crashes when the definition of an existing `snowflake_resource_monitor` is updated to use the new `suspend_trigger` attribute from the deprecated `suspend_triggers` attribution and is applied to an existing resource .

**Expected behavior**

The resource should gracefully updated.

**Code samples and commands**

Apply resource using deprecated attributes
```tf
resource "snowflake_resource_monitor" "test" {
  name         = "TEST"
  credit_quota = "100"

  set_for_account = true

  suspend_triggers = [200]
}
```

Amend to use new one and apply
```tf
resource "snowflake_resource_monitor" "test" {
  name         = "TEST"
  credit_quota = "100"

  set_for_account = true

  suspend_trigger = 200
}
```
Observe plugin crash
```sh
snowflake_resource_monitor.test: Modifying... [id=TEST]
╷
│ Error: Plugin did not respond
│ 
│   with snowflake_resource_monitor.test,
│   on main.tf line 90, in resource "snowflake_resource_monitor" "test":
│   90: resource "snowflake_resource_monitor" "test" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-snowflake_v0.60.0 plugin:

panic: interface conversion: interface {} is *schema.Set, not int

goroutine 65 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.UpdateResourceMonitor(0x14000b9aa80, {0x1057a8fc0?, 0x140005c3520})
        github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/resource_monitor.go:380 +0x173c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x1057d31c0?, {0x1057d31c0?, 0x140005f8cf0?}, 0xd?, {0x1057a8fc0?, 0x140005c3520?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:729 +0x134
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x1400071a0e0, {0x1057d31c0, 0x140005f8cf0}, 0x14000b9e5b0, 0x14000b9a900, {0x1057a8fc0, 0x140005c3520})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:847 +0x67c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x14000703638, {0x1057d31c0?, 0x140005f8bd0?}, 0x140005fe2d0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:1021 +0xb70
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x140000d5860, {0x1057d31c0?, 0x140005f81b0?}, 0x14000b94070)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x3b8
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x105770360?, 0x140000d5860}, {0x1057d31c0, 0x140005f81b0}, 0x14000b94000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x140002381e0, {0x1057d9600, 0x140001161a0}, 0x14000b84000, 0x140007142d0, 0x10604d9a0, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1336 +0xb7c
google.golang.org/grpc.(*Server).handleStream(0x140002381e0, {0x1057d9600, 0x140001161a0}, 0x14000b84000, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1704 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.53.0/server.go:965 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.53.0/server.go:963 +0x290

Error: The terraform-provider-snowflake_v0.60.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Additional context**

**Comment by bennylu2** [comment]
Thanks for reporting this!

I believe I have addressed with this commit https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1682/commits/f7ac6cc104a0e114bfc8b3e2eb12cd1ed61c689c

**Comment by joshuaghezzi** [comment]
Thanks, looks like that should do it.

**Comment by funes79** [comment]
I have the same issue, using `0.61.0` so I dont think it is fixed.
Using terraform 1.4.5

```
Error: Request cancelled
│ 
│   with snowflake_resource_monitor.monitor["MY_WAREHOUSE"],
│   on warehouses_monitoring.tf line 14, in resource "snowflake_resource_monitor" "monitor":
│   14: resource "snowflake_resource_monitor" "monitor" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
│   with snowflake_resource_monitor.monitor["MY_WAREHOUSE"],
│   on warehouses_monitoring.tf line 14, in resource "snowflake_resource_monitor" "monitor":
│   14: resource "snowflake_resource_monitor" "monitor" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

Stack trace from the terraform-provider-snowflake_v0.61.0 plugin:

panic: interface conversion: interface {} is *schema.Set, not int

goroutine 59 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.UpdateResourceMonitor(0xc000c98580, {0x14c6120?, 0xc0007fb040})
        github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/resource_monitor.go:380 +0x1cfb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x176fca0?, {0x176fca0?, 0xc0002d9fb0?}, 0xd?, {0x14c6120?, 0xc0007fb040?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:729 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00095e1c0, {0x176fca0, 0xc0002d9fb0}, 0xc000c245b0, 0xc000c98400, {0x14c6120, 0xc0007fb040})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:847 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00093ab58, {0x176fca0?, 0xc0002d9e90?}, 0xc0005284b0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0001463c0, {0x176fca0?, 0xc0002d9650?}, 0xc000846070)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x148cc40?, 0xc0001463c0}, {0x176fca0, 0xc0002d9650}, 0xc000846000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00094e000, {0x1776440, 0xc0006084e0}, 0xc0006685a0, 0xc00094ab70, 0x2046da0, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc00094e000, {0x1776440, 0xc0006084e0}, 0xc0006685a0, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

Error: The terraform-provider-snowflake_v0.61.0 plugin crashed!
```
