### ISSUE TITLE
Error when updating external OAuth integration

### ISSUE THREAD

**Issue by calleo** [Snowflake-Labs/terraform-provider-snowflake#1851]
**Provider Version**

0.65

**Terraform Version**

1.3.9

**Describe the bug**

I have created an external oauth integration using the resource "snowflake_external_oauth_integration".

Later I want to change the default value of "any_role_mode", so I add it to the resource which triggers an update of the oauth integration.

Running `plan` works as expected:

```
Terraform will perform the following actions:

  # module.snowflake_sso.snowflake_external_oauth_integration.power_bi_oauth will be updated in-place
  ~ resource "snowflake_external_oauth_integration" "power_bi_oauth" {
      ~ any_role_mode                    = "DISABLE" -> "ENABLE"
        id                               = "AZURE_POWERBI"
        name                             = "AZURE_POWERBI"
        # (10 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

But when running `apply`, terraform fails with the following error:

```
Stack trace from the terraform-provider-snowflake_v0.65.0 plugin:

panic: interface conversion: interface {} is string, not snowflake.AnyRoleMode

goroutine 47 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.UpdateExternalOauthIntegration(0x0?, {0x15ce4c0?, 0xc000a53450})
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/external_oauth_integration.go:478 +0x104c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x18d1020?, {0x18d1020?, 0xc0008c7ec0?}, 0xd?, {0x15ce4c0?, 0xc000a53450?})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:729 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0007f0c40, {0x18d1020, 0xc0008c7ec0}, 0xc000661520, 0xc000059580, {0x15ce4c0, 0xc000a53450})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:847 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000595c08, {0x18d1020?, 0xc0008c7da0?}, 0xc0004d5310)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000120320, {0x18d1020?, 0xc0008c7260?}, 0xc00026c9a0)
github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1591180?, 0xc000120320}, {0x18d1020, 0xc0008c7260}, 0xc00026c8c0, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000b4960, {0x18d7f60, 0xc000007380}, 0xc000792a20, 0xc00014a330, 0x22844e0, 0x0)
google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc0000b4960, {0x18d7f60, 0xc000007380}, 0xc000792a20, 0x0)
google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

Error: The terraform-provider-snowflake_v0.65.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Expected behavior**

Terraform should be able to update the external oauth integration in-place.

If I instead drop the external oauth integration and re-create it with any_role_mode set to "ENABLE", things work. So this issue is only related to updating an existing resource.

**Code samples and commands**

See above.

**Additional context**

N/A

**Comment by kalinon** [comment]
I also encounter this behavior:

```
panic: interface conversion: interface {} is string, not snowflake.AnyRoleMode

goroutine 105 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.UpdateExternalOauthIntegration(0x0?, {0x10226e760?, 0x1400053cc30})
	github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/external_oauth_integration.go:478 +0xda0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x1022ac8c0?, {0x1022ac8c0?, 0x14000f6cd20?}, 0xd?, {0x10226e760?, 0x1400053cc30?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:800 +0x134
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x140000cb180, {0x1022ac8c0, 0x14000f6cd20}, 0x14000f52820, 0x14000f8c080, {0x10226e760, 0x1400053cc30})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:919 +0x6b0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x14000bac210, {0x1022ac8c0?, 0x14000f6cc00?}, 0x14000f23950)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:1060 +0xb78
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x14000a5a280, {0x1022ac8c0?, 0x14000f6c3f0?}, 0x14000f4a310)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:859 +0x3bc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x102221ca0?, 0x14000a5a280}, {0x1022ac8c0, 0x14000f6c3f0}, 0x14000f4a2a0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:467 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400085ed20, {0x1022bbe20, 0x14000602ea0}, 0x14000f5f440, 0x14000bc6000, 0x102e68c78, 0x0)
	google.golang.org/grpc@v1.57.0/server.go:1360 +0xcb4
google.golang.org/grpc.(*Server).handleStream(0x1400085ed20, {0x1022bbe20, 0x14000602ea0}, 0x14000f5f440, 0x0)
	google.golang.org/grpc@v1.57.0/server.go:1737 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.57.0/server.go:982 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.57.0/server.go:980 +0x16c
panic: interface conversion: interface {} is string, not snowflake.AnyRoleMode
```

**Comment by sfc-gh-jmichalak** [comment]
Hey @calleo @kalinon   👋
The new version [v0.93.0](https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v0.93.0) provides adjusted `external_oauth_integration`. Now, `external_oauth_any_role_mode` is handled correctly, so please migrate from `externaloauth_integration`. Please follow [the migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md#snowflake_external_oauth_integration-resource-changes).
