### ISSUE TITLE
The terraform-provider-snowflake_v0.68.2 plugin crashed

### ISSUE THREAD

**Issue by GomathiMa** [Snowflake-Labs/terraform-provider-snowflake#1999]
**68.2**

The provider version you are using.

**Terraform Version**

The version of Terraform you were using when the bug was encountered.

**The terraform-provider-snowflake_v0.68.2 plugin crashed during terraform apply in github actions**

**Expected behavior**

**Code samples and commands**

Please add code examples and commands that were run to cause the problem.

**Additional context**

**Comment by chrisweis** [comment]
I got this similar error on v0.69 also.

The resource:
```
resource "snowflake_grant_privileges_to_role" "DEV_DW_DB__DW_BI__FUTURE" {
  privileges = ["SELECT"]
  role_name = "ACCOUNTADMIN"
  on_schema_object {
    future {
        object_type_plural = "VIEWS"
        in_schema = snowflake_schema.DW_BI.name
    }
  }
}
```

The error:
```
Do you want to perform these actions in workspace "snowflake-terraform-dbt-api-dev"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

snowflake_view_grant.DEV_DW_DB__DW_BI__FUTURE: Destroying... [id=DEV_DW_DB|DW_BI||SELECT|true|true|false|ACCOUNTADMIN|]
snowflake_grant_privileges_to_role.DEV_DW_DB__DW_BI__FUTURE: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with snowflake_grant_privileges_to_role.DEV_DW_DB__DW_BI__FUTURE,
│   on grant_privileges_to_role.tf line 13, in resource "snowflake_grant_privileges_to_role" "DEV_DW_DB__DW_BI__FUTURE":
│   13: resource "snowflake_grant_privileges_to_role" "DEV_DW_DB__DW_BI__FUTURE" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-snowflake_v0.69.0 plugin:

panic: runtime error: index out of range [1] with length 1

goroutine 40 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk.NewSchemaIdentifierFromFullyQualifiedName({0xc000d0d530?, 0xc00090c000?})
        github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk/identifier_helpers.go:149 +0xcc
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.configureAccountRoleGrantPrivilegeOptions(0xc00076d480?, {0xc000ab9150, 0x1, 0x1}, 0x1?, 0xc000920dd0)
        github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/grant_privileges_to_role.go:779 +0x12f3
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.CreateGrantPrivilegesToRole(0x0?, {0x15e7a40?, 0xc0005b2d00})
        github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/grant_privileges_to_role.go:453 +0x1c5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x18eb540?, {0x18eb540?, 0xc000a78ae0?}, 0xd?, {0x15e7a40?, 0xc0005b2d00?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0008315e0, {0x18eb540, 0xc000a78ae0}, 0xc000a00a90, 0xc000cfc380, {0x15e7a40, 0xc0005b2d00})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0007b62a0, {0x18eb540?, 0xc000a789c0?}, 0xc0000b2190)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00086ee60, {0x18eb540?, 0xc000a78180?}, 0xc000462310)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x15a9bc0?, 0xc00086ee60}, {0x18eb540, 0xc000a78180}, 0xc0004620e0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000ba960, {0x18f2520, 0xc000603a00}, 0xc000cf6000, 0xc000545200, 0x22a2760, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc0000ba960, {0x18f2520, 0xc000603a00}, 0xc000cf6000, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

Error: The terraform-provider-snowflake_v0.69.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

Operation failed: failed running terraform apply (exit 1)
```

**Comment by GomathiMa** [comment]
Issue resolved after using the correct syntax for schema name as per terraform registry[for example in_schema = "\"DEV_DW_DB\".\"DW_BI\""]
