### ISSUE TITLE
Cannot create a snowflake_user with provider 0.70.1

### ISSUE THREAD

**Issue by amasliah-rbi** [Snowflake-Labs/terraform-provider-snowflake#2058]
**Provider Version**

0.70.1
terraform-provider-snowflake_v0.70.1

**Terraform Version**

Terraform v1.1.9

**Describe the bug**

Creating a new snowflake user resource fails on apply with a plugin did not respond error.

Example plan:
```
# module.account.snowflake_user.user will be created
  + resource "snowflake_user" "user" {
      + default_role       = "ROLE"
      + default_warehouse  = "WAREHOUSE"
      + disabled           = false
      + display_name       = (sensitive value)
      + email              = (sensitive value)
      + first_name         = (sensitive value)
      + has_rsa_public_key = (known after apply)
      + id                 = (known after apply)
      + last_name          = (sensitive value)
      + login_name         = (known after apply)
      + name               = (sensitive value)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

After applying
```
Error: Plugin did not respond
│
│   with module.account.snowflake_user.user,
│   on ../../../modules/account/users.tf line 1344, in resource "snowflake_user" "user":
│ 1344: resource "snowflake_user" "user" {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.

Stack trace from the terraform-provider-snowflake_v0.70.1 plugin:

panic: interface conversion: sdk.ObjectIdentifier is sdk.DatabaseObjectIdentifier, not sdk.AccountObjectIdentifier

goroutine 85 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.ReadUser(0xc00050d600, {0x1ac67c0?, 0xc000b40000?})
	github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/user.go:244 +0x96a
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.CreateUser(0x0?, {0x1ac67c0?, 0xc000b40000?})
	github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/user.go:236 +0xbc8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1de2900?, {0x1de2900?, 0xc000e7b7d0?}, 0xd?, {0x1ac67c0?, 0xc000b40000?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00025cc40, {0x1de2900, 0xc000e7b7d0}, 0xc00087cdd0, 0xc00050d480, {0x1ac67c0, 0xc000b40000})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000277920, {0x1de2900?, 0xc000e7b6b0?}, 0xc00019a640)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00085c640, {0x1de2900?, 0xc000e7acc0?}, 0xc000aabe30)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1a79800?, 0xc00085c640}, {0x1de2900, 0xc000e7acc0}, 0xc000aabdc0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000768960, {0x1df22c0, 0xc0008e0000}, 0xc000526fc0, 0xc0005afe30, 0x2a3c3e0, 0x0)
	google.golang.org/grpc@v1.53.0/server.go:1336 +0xd33
google.golang.org/grpc.(*Server).handleStream(0xc000768960, {0x1df22c0, 0xc0008e0000}, 0xc000526fc0, 0x0)
	google.golang.org/grpc@v1.53.0/server.go:1704 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

Error: The terraform-provider-snowflake_v0.70.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

Operation failed: failed running terraform apply (exit 1)
```

**Expected behavior**

Expected user to be created in Snowflake without an error - sometimes the user is created sometimes it is not.

**Code samples and commands**

Example TF code:
```
resource "snowflake_user" "user" {
  name     = "USER"
  email    = "USER@EMAIL.COM"
  disabled = false

  first_name   = "Test"
  last_name    = "User"
  display_name = "Test User"

  default_warehouse = "WAREHOUSE"
  default_role      = "ROLE"
}
```

**Comment by avivn-gloat** [comment]
@amasliah-rbi any updates on this? did you try earlier versions that can be applied to fix this?

**Comment by kolyarice** [comment]
I'm getting a similar error as well, with 0.74
Although the plugin crashed, _some_ user resources were provisioned
Rolling back to 0.69 allowed the apply to succeed, though it subsequently failed when two of the four users existed already (I manually imported them to state)

`Stack trace from the terraform-provider-snowflake_v0.74.0 plugin:
panic: interface conversion: sdk.ObjectIdentifier is sdk.TableColumnIdentifier, not sdk.AccountObjectIdentifier
goroutine 112 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.ReadUser(0xc0005b1980, {0x1c66fc0?, 0xc0005b6a90?})
	github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/user.go:244 +0x96a
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.CreateUser(0x0?, {0x1c66fc0?, 0xc0005b6a90?})
	github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/user.go:236 +0xbc8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1fb9f80?, {0x1fb9f80?, 0xc0007dd2c0?}, 0xd?, {0x1c66fc0?, 0xc0005b6a90?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:766 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0001f5880, {0x1fb9f80, 0xc0007dd2c0}, 0xc0005b7380, 0xc0005b1800, {0x1c66fc0, 0xc0005b6a90})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:909 +0xa7e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000e90018, {0x1fb9f80?, 0xc0007dd1a0?}, 0xc0007f2410)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:1060 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000e9a000, {0x1fb9f80?, 0xc0007dc990?}, 0xc0005b8a80)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:859 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1c16380?, 0xc000e9a000}, {0x1fb9f80, 0xc0007dc990}, 0xc0005b8a10, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:467 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000314a0, {0x1fc9c00, 0xc000e84b60}, 0xc0007ab9e0, 0xc000e881b0, 0x2cc4558, 0x0)
	google.golang.org/grpc@v1.58.2/server.go:1376 +0xdd2
google.golang.org/grpc.(*Server).handleStream(0xc0000314a0, {0x1fc9c00, 0xc000e84b60}, 0xc0007ab9e0, 0x0)
	google.golang.org/grpc@v1.58.2/server.go:1753 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.58.2/server.go:998 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.58.2/server.go:996 +0x18c
Error: The terraform-provider-snowflake_v0.74.0 plugin crashed!`

**Comment by adamhealy** [comment]
I'm having the same issue with the provider from version 0.70.1 up to 0.73.0:

```
Stack trace from the terraform-provider-snowflake_v0.73.0 plugin:

panic: interface conversion: sdk.ObjectIdentifier is sdk.SchemaObjectIdentifier, not sdk.AccountObjectIdentifier

goroutine 40 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.ReadUser(0xc00064b980, {0x1b6e6a0?, 0xc000882680?})
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/user.go:244 +0x96a
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.CreateUser(0x0?, {0x1b6e6a0?, 0xc000882680?})
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/user.go:236 +0xbc8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1ea1900?, {0x1ea1900?, 0xc000ca0090?}, 0xd?, {0x1b6e6a0?, 0xc000882680?})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:766 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000739ea0, {0x1ea1900, 0xc000ca0090}, 0xc000752f70, 0xc00064b800, {0x1b6e6a0, 0xc000882680})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:909 +0xa7e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000871dd0, {0x1ea1900?, 0xc000c87f50?}, 0xc000674c80)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:1060 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0000f7b80, {0x1ea1900?, 0xc000c87560?}, 0xc00068b340)
github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:859 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1b1fda0?, 0xc0000f7b80}, {0x1ea1900, 0xc000c87560}, 0xc00068b2d0, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:467 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000696d20, {0x1eb1480, 0xc00073e1a0}, 0xc000c8f320, 0xc000643050, 0x2b61258, 0x0)
google.golang.org/grpc@v1.57.0/server.go:1360 +0xe23
google.golang.org/grpc.(*Server).handleStream(0xc000696d20, {0x1eb1480, 0xc00073e1a0}, 0xc000c8f320, 0x0)
google.golang.org/grpc@v1.57.0/server.go:1737 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.1()
google.golang.org/grpc@v1.57.0/server.go:982 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
google.golang.org/grpc@v1.57.0/server.go:980 +0x18c

Error: The terraform-provider-snowflake_v0.73.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by ric-sylvera** [comment]
I had the same error on v0.73.0 and v0.75.0. All users were added to the account but the final user was not added to the state and the apply failed.

**Comment by sfc-gh-jcieslak** [comment]
@amasliah-rbi @avivn-gloat @kolyarice @adamhealy @ric-sylvera 
Hey, I've run the given example in the versions you mentioned and it worked.

The error mentions the wrong identifier. As far as I checked the error may occur when user.name contains pipe characters `|` or dots `.`

We would like to address the issues with the identifiers soon, but for now, I would recommend not using them. Other separators like dash `-` or underscore `_` should work.
