### ISSUE TITLE
Plugin crashes when upating `snowflake_resource_monitor`

### ISSUE THREAD

**Issue by kalinon** [Snowflake-Labs/terraform-provider-snowflake#2167]
**Provider Version**

`v0.72.0`

**Terraform Version**

`1.6.2`

**Describe the bug**

When trying to add a new user to `snowflake_resource_monitor` it crashes.

**Expected behavior**

It should update the resource monitor with the additional user

**Code samples and commands**

The error occured when adding `User2` to `notify_users`

```
resource "snowflake_resource_monitor" "demo" {
  name         = snowflake_warehouse.demo.name
  credit_quota = 5

  frequency       = "DAILY"
  start_timestamp = "2023-11-01T17:00:00-07:00"
  end_timestamp   = "2024-10-31T17:00:00-07:00"

  notify_triggers           = [75]
  suspend_trigger           = 85
  suspend_immediate_trigger = 95

  notify_users = ["User1", "User2"]
  warehouses   = [snowflake_warehouse.demo.name]
}
```

**Additional context**

```
snowflake_resource_monitor.demo: Modifying... [id=DEMO_WH]
╷
│ Error: Request cancelled
│
│   with snowflake_resource_monitor.demo,
│   on demo.tf line 7, in resource "snowflake_resource_monitor" "demo":
│    7: resource "snowflake_resource_monitor" "demo" {
│
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

Stack trace from the terraform-provider-snowflake_v0.72.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x103669608]

goroutine 16 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.UpdateResourceMonitor(0x14000f38300, {0x103f6a760?, 0x14000b0e340?})
	github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/resource_monitor.go:346 +0x1448
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x103fa88c0?, {0x103fa88c0?, 0x14000f2e870?}, 0xd?, {0x103f6a760?, 0x14000b0e340?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:800 +0x134
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x1400061fb20, {0x103fa88c0, 0x14000f2e870}, 0x14000ef5040, 0x14000f38180, {0x103f6a760, 0x14000b0e340})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:919 +0x6b0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x14000c92018, {0x103fa88c0?, 0x14000f2e750?}, 0x14000f14820)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:1060 +0xb78
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x14000c9c000, {0x103fa88c0?, 0x14000f03d40?}, 0x14000edb0a0)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:859 +0x3bc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x103f1dca0?, 0x14000c9c000}, {0x103fa88c0, 0x14000f03d40}, 0x14000edb030, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:467 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000780d20, {0x103fb7e20, 0x14000c0cb60}, 0x14000e41560, 0x14000c8a180, 0x104b64c78, 0x0)
	google.golang.org/grpc@v1.57.0/server.go:1360 +0xcb4
google.golang.org/grpc.(*Server).handleStream(0x14000780d20, {0x103fb7e20, 0x14000c0cb60}, 0x14000e41560, 0x0)
	google.golang.org/grpc@v1.57.0/server.go:1737 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.57.0/server.go:982 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.57.0/server.go:980 +0x16c

Error: The terraform-provider-snowflake_v0.72.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by kalinon** [comment]
Also on `0.73.0`

**Comment by catherine-v** [comment]
Also on `0.80.0` for me

**Comment by vgw-rubesh** [comment]
I am on 0.77.0 and have the same error:

**Comment by sfc-gh-asawicki** [comment]
Hey @kalinon. Thanks for reporting the issue.

The fix should be really simple, I will add this today (if it is really as simple as it seems, we will add it to the nearest release).
