### ISSUE TITLE
Snowflake Provider v0.69.0 Plugin Crashing with Integration Change

### ISSUE THREAD

**Issue by JCopeland-RBI** [Snowflake-Labs/terraform-provider-snowflake#2177]
**Provider Version**

`0.69.0`

**Terraform Version**

`1.1.9`

**Describe the bug**

When attempting to make changes to a Snowflake OAuth Integration, the plugin throws a panic error and the plugin does not repond. Only broken for one module. 

**Expected behavior**

Expected for the small changes to apply instead of the plugin breaking. 

**Code samples and commands**
Error received below: 

```
module.use1.snowflake_oauth_integration.sprinklr: Modifying... [id=SPRINKLR]
╷
│ Error: Plugin did not respond
│ 
│   with module.use1.snowflake_oauth_integration.sprinklr,
│   on ../../../modules/sprinklr/security_integrations.tf line 1, in resource "snowflake_oauth_integration" "sprinklr":
│    1: resource "snowflake_oauth_integration" "sprinklr" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-snowflake_v0.69.0 plugin:

panic: interface conversion: interface {} is *schema.Set, not []interface {}

goroutine 85 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.UpdateOAuthIntegration(0xc0001a7000, {0x15e7a40?, 0xc000a1a9c0})
        github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/oauth_integration.go:313 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x18eb540?, {0x18eb540?, 0xc000d54cf0?}, 0xd?, {0x15e7a40?, 0xc000a1a9c0?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:729 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0007a3c00, {0x18eb540, 0xc000d54cf0}, 0xc000d6e4e0, 0xc0001a6d80, {0x15e7a40, 0xc000a1a9c0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:847 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000721e30, {0x18eb540?, 0xc000d54bd0?}, 0xc0004ea2d0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0007c8fa0, {0x18eb540?, 0xc000d541b0?}, 0xc000a5e070)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x15a9bc0?, 0xc0007c8fa0}, {0x18eb540, 0xc000d541b0}, 0xc000a5e000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000a6960, {0x18f2520, 0xc0005831e0}, 0xc000d5c000, 0xc00059eba0, 0x22a2760, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc0000a6960, {0x18f2520, 0xc0005831e0}, 0xc000d5c000, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

Error: The terraform-provider-snowflake_v0.69.0 plugin crashed!

```

**Comment by sfc-gh-jmichalak** [comment]
Hey @JCopeland-RBI  👋
The new version [v0.93.0](https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v0.93.0) provides new resources for oauth: `oauth_integration_for_custom_clients` and `oauth_integration_for_partner_applications`. These resources handle `blocked_list` correctly, so please migrate from `oauth_integration` to one of them. Please follow [the migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md#new-feature-snowflake_oauth_integration_for_custom_clients-and-snowflake_oauth_integration_for_partner_applications-resources).
