### ISSUE TITLE
Missing import documentation for role_ownership_grant

### ISSUE THREAD

**Issue by bert-ciandt** [Snowflake-Labs/terraform-provider-snowflake#2178]
**Provider Version**

0.69.0

**Terraform Version**

1.6.2

**Describe the bug**

There isn't any documentation on how to import a role_ownership_grant.

**Expected behavior**

Other resources have clear instructions how to import them. This one is missing that.

**Additional context**

https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/role_ownership_grant

**Comment by sfc-gh-asawicki** [comment]
Hey @bert-ciandt. Thanks for creating the issue.

There is a small typo in the example directory which makes the documentation not generating correctly. You can access the example directly here: https://github.com/Snowflake-Labs/terraform-provider-snowflake/tree/01a774c564e4a74dea41385ddf775b7f9e9d1f7b/examples/resources/snowflake_role_ownership_grants. The fix is on its way: #2183

**Comment by bert-ciandt** [comment]
The example seems to be incorrect. Using the on_role_name for roleName gives this:

```Stack trace from the terraform-provider-snowflake_v0.75.0 plugin:

panic: runtime error: index out of range [2] with length 1

goroutine 324 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.ReadRoleOwnershipGrant(0x140009a8600, {0x1041f0d20?, 0x14000ba5e10})
	github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/role_ownership_grant.go:90 +0x698
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x104231840?, {0x104231840?, 0x140009d1500?}, 0xd?, {0x1041f0d20?, 0x14000ba5e10?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:783 +0x134
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x140005d48c0, {0x104231840, 0x140009d1500}, 0x14000a2c340, {0x1041f0d20, 0x14000ba5e10})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:1089 +0x494
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x14000ca0b88, {0x104231840?, 0x140009d13e0?}, 0x14000b70d40)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:649 +0x400
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x14000b72000, {0x104231840?, 0x140009d0900?}, 0x14000ab67e0)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:789 +0x3e8
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x1041a0ee0?, 0x14000b72000}, {0x104231840, 0x140009d0900}, 0x14000bea000, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:431 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400003d680, {0x104240ee0, 0x14000102d00}, 0x140009d2360, 0x14000bd1f20, 0x104e44ec8, 0x0)
	google.golang.org/grpc@v1.58.2/server.go:1376 +0xbe0
google.golang.org/grpc.(*Server).handleStream(0x1400003d680, {0x104240ee0, 0x14000102d00}, 0x140009d2360, 0x0)
	google.golang.org/grpc@v1.58.2/server.go:1753 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.58.2/server.go:998 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.58.2/server.go:996 +0x16c

Error: The terraform-provider-snowflake_v0.75.0 plugin crashed!
```
and using the to_role_name gives this:

```
Stack trace from the terraform-provider-snowflake_v0.75.0 plugin:

panic: runtime error: index out of range [2] with length 1

goroutine 245 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.ReadRoleOwnershipGrant(0x14000677080, {0x103988d20?, 0x140008401a0})
	github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/role_ownership_grant.go:90 +0x698
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x1039c9840?, {0x1039c9840?, 0x14000ea3800?}, 0xd?, {0x103988d20?, 0x140008401a0?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:783 +0x134
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x14000632460, {0x1039c9840, 0x14000ea3800}, 0x1400089d040, {0x103988d20, 0x140008401a0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:1089 +0x494
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x140006e5398, {0x1039c9840?, 0x14000ea36e0?}, 0x140006d5700)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:649 +0x400
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x140006d2500, {0x1039c9840?, 0x14000ea2d20?}, 0x1400091ede0)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:789 +0x3e8
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x103938ee0?, 0x140006d2500}, {0x1039c9840, 0x14000ea2d20}, 0x140009f85b0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:431 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400003d4a0, {0x1039d8ee0, 0x14000c029c0}, 0x14000ea6900, 0x14000629200, 0x1045dcec8, 0x0)
	google.golang.org/grpc@v1.58.2/server.go:1376 +0xbe0
google.golang.org/grpc.(*Server).handleStream(0x1400003d4a0, {0x1039d8ee0, 0x14000c029c0}, 0x14000ea6900, 0x0)
	google.golang.org/grpc@v1.58.2/server.go:1753 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.58.2/server.go:998 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.58.2/server.go:996 +0x16c

Error: The terraform-provider-snowflake_v0.75.0 plugin crashed!
```

**Comment by bert-ciandt** [comment]
Documentation now appears in Registry. Thanks! Opening new ticket for import problem.
