### ISSUE TITLE
Snowpipes - terraform-provider-snowflake_v0.76.0 plugin:

### ISSUE THREAD

**Issue by messi198310** [Snowflake-Labs/terraform-provider-snowflake#2224]
### Terraform CLI and Provider Versions

 terraform-provider-snowflake_v0.76.0 plugin:

### Terraform Configuration

```terraform
Error: error granting privileges to account role: 003111 (0A000): SQL compilation error:
Bulk grant on objects of type PIPE to ROLE is restricted.

resource "snowflake_grant_privileges_to_role" "snowpipe_grants" {
provider = snowflake.security_admin
privileges = ["OPERATE"]
role_name = var.roles["raw_admin"].name
on_schema_object {
all {
object_type_plural = "PIPES"
in_schema = ""${snowflake_database.dw_db.name}"."${var.schemas.raw_dynamodb.name}""
}
}
}

I have just had a crash with the same plugin updating grants on Snowpipes,Functions and file formats from the old method to the new snowflake_grant_privileges_to_role resource

Stack trace from the terraform-provider-snowflake_v0.76.0 plugin:

panic: runtime error: index out of range [1] with length 1

goroutine 71 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk.NewSchemaObjectIdentifierFromFullyQualifiedName({0xc0009ed458?, 0xc000c893e0?})
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk/identifier_helpers.go:206 +0x46a
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.configureAccountRoleGrantPrivilegeOptions(0xc000c9a2e0?, {0xc000c8f330, 0x1, 0x1}, 0x1?, 0xc000b56cf0)
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/grant_privileges_to_role.go:746 +0xd85
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.CreateGrantPrivilegesToRole(0x0?, {0x1ced480?, 0xc0009211e0?})
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/grant_privileges_to_role.go:456 +0x1ad
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x2054060?, {0x2054060?, 0xc000b3ce10?}, 0xd?, {0x1ced480?, 0xc0009211e0?})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:766 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0000dee00, {0x2054060, 0xc000b3ce10}, 0xc000b5c820, 0xc000711080, {0x1ced480, 0xc0009211e0})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:909 +0xa7e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0007499f8, {0x2054060?, 0xc000b3cc30?}, 0xc000b09d60)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:1060 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ApplyResourceChange({{0x2073560?, 0xc0007499f8?}}, {0x2054060, 0xc000b3cc30}, 0x0?)
github.com/hashicorp/terraform-plugin-mux@v0.12.0/tf5to6server/tf5to6server.go:37 +0x5a
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ApplyResourceChange(0x2053fb8?, {0x2054060?, 0xc000b3c900?}, 0xc000b09d10)
github.com/hashicorp/terraform-plugin-mux@v0.12.0/tf6muxserver/mux_server_ApplyResourceChange.go:36 +0x1b5
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc0007a0640, {0x2054060?, 0xc000ad9920?}, 0xc000b94cb0)
github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov6/tf6server/server.go:857 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x1c998c0?, 0xc0007a0640}, {0x2054060, 0xc000ad9920}, 0xc000b94c40, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:467 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0005632c0, {0x2063ec0, 0xc0009a04e0}, 0xc000b00b40, 0xc000778d80, 0x2d7e8d8, 0x0)
google.golang.org/grpc@v1.58.2/server.go:1376 +0xdd2
google.golang.org/grpc.(*Server).handleStream(0xc0005632c0, {0x2063ec0, 0xc0009a04e0}, 0xc000b00b40, 0x0)
google.golang.org/grpc@v1.58.2/server.go:1753 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.1()
google.golang.org/grpc@v1.58.2/server.go:998 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
google.golang.org/grpc@v1.58.2/server.go:996 +0x18c
```

### Expected Behavior

Error: error granting privileges to account role: 003111 (0A000): SQL compilation error:
Bulk grant on objects of type PIPE to ROLE is restricted.

### Actual Behavior

Error: error granting privileges to account role: 003111 (0A000): SQL compilation error:
Bulk grant on objects of type PIPE to ROLE is restricted.

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

High

**Comment by messi198310** [comment]
I have just had a crash with the same plugin updating grants on Snowpipes,Functions and file formats from the old method to the new snowflake_grant_privileges_to_role resource

Stack trace from the terraform-provider-snowflake_v0.76.0 plugin:

panic: runtime error: index out of range [1] with length 1

goroutine 71 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk.NewSchemaObjectIdentifierFromFullyQualifiedName({0xc0009ed458?, 0xc000c893e0?})
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk/identifier_helpers.go:206 +0x46a
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.configureAccountRoleGrantPrivilegeOptions(0xc000c9a2e0?, {0xc000c8f330, 0x1, 0x1}, 0x1?, 0xc000b56cf0)
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/grant_privileges_to_role.go:746 +0xd85
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.CreateGrantPrivilegesToRole(0x0?, {0x1ced480?, 0xc0009211e0?})
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/grant_privileges_to_role.go:456 +0x1ad
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x2054060?, {0x2054060?, 0xc000b3ce10?}, 0xd?, {0x1ced480?, 0xc0009211e0?})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:766 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0000dee00, {0x2054060, 0xc000b3ce10}, 0xc000b5c820, 0xc000711080, {0x1ced480, 0xc0009211e0})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:909 +0xa7e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0007499f8, {0x2054060?, 0xc000b3cc30?}, 0xc000b09d60)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:1060 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ApplyResourceChange({{0x2073560?, 0xc0007499f8?}}, {0x2054060, 0xc000b3cc30}, 0x0?)
github.com/hashicorp/terraform-plugin-mux@v0.12.0/tf5to6server/tf5to6server.go:37 +0x5a
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ApplyResourceChange(0x2053fb8?, {0x2054060?, 0xc000b3c900?}, 0xc000b09d10)
github.com/hashicorp/terraform-plugin-mux@v0.12.0/tf6muxserver/mux_server_ApplyResourceChange.go:36 +0x1b5
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc0007a0640, {0x2054060?, 0xc000ad9920?}, 0xc000b94cb0)
github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov6/tf6server/server.go:857 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x1c998c0?, 0xc0007a0640}, {0x2054060, 0xc000ad9920}, 0xc000b94c40, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:467 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0005632c0, {0x2063ec0, 0xc0009a04e0}, 0xc000b00b40, 0xc000778d80, 0x2d7e8d8, 0x0)
google.golang.org/grpc@v1.58.2/server.go:1376 +0xdd2
google.golang.org/grpc.(*Server).handleStream(0xc0005632c0, {0x2063ec0, 0xc0009a04e0}, 0xc000b00b40, 0x0)
google.golang.org/grpc@v1.58.2/server.go:1753 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.1()
google.golang.org/grpc@v1.58.2/server.go:998 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
google.golang.org/grpc@v1.58.2/server.go:996 +0x18c

**Comment by sfc-gh-jcieslak** [comment]
@messi198310 
Hey 👋 
It seems like the identifier at `object_name = snowflake_file_format.dynamodb_json_format.name` is invalid. 

Here, we expect a fully qualified name with 3 parts `"database_name"."schema_name"."schema_object"` and it seems like there's only one part (I'm guessing "schema_object"). 

When specifying IDs with quotes in HCL remember to escape the string like this:
`object_name = "\"database_name\".\"schema_name\".\"schema_object\""`
or if all of the identifiers are case insensitive you can omit the quotes like this:
`object_name = "database_name.schema_name.schema_object"`

It depends on your setup, but making the identifier fully qualified should resolve the issue. 
If that's the case, please let me know.
