### ISSUE TITLE
 terraform import failing for schema

### ISSUE THREAD

**Issue by peterspiro** [Snowflake-Labs/terraform-provider-snowflake#2349]
### Terraform CLI and Provider Versions

Terraform v1.6.6
on darwin_amd64
+ provider registry.terraform.io/snowflake-labs/snowflake v0.83.1

### Terraform Configuration

```terraform
resource "snowflake_schema" "elt_metadata" {
  database     = local.database_name
  name         = "ELT_METADATA"
  is_transient = true
}
```

### Expected Behavior

Import should succeed when the schema exists.

### Actual Behavior

Import failed with the message:
```
$ terraform import snowflake_schema.elt_metadata ELT_METADATA
snowflake_schema.elt_metadata: Importing from ID "ELT_METADATA"...
snowflake_schema.elt_metadata: Import prepared!
  Prepared snowflake_schema for import
snowflake_schema.elt_metadata: Refreshing state... [id=ELT_METADATA]
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵


Stack trace from the terraform-provider-snowflake_v0.83.1 plugin:

panic: interface conversion: sdk.ObjectIdentifier is sdk.AccountObjectIdentifier, not sdk.DatabaseObjectIdentifier

goroutine 27 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.ReadSchema(0xc000e9cd80, {0x2b9a640?, 0xc000b65450?})
	github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/schema.go:108 +0x84a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x2f19688?, {0x2f19688?, 0xc000c77d10?}, 0xd?, {0x2b9a640?, 0xc000b65450?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:783 +0x163
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000aba000, {0x2f19688, 0xc000c77d10}, 0xc000c511e0, {0x2b9a640, 0xc000b65450})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:1089 +0x552
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0008ef0f8, {0x2f19688?, 0xc000c77bc0?}, 0xc000e83000)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/grpc_provider.go:663 +0x48a
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ReadResource({{0x2f2eac0?, 0xc0008ef0f8?}}, {0x2f19688?, 0xc000c77bc0?}, 0xc000e82e80?)
	github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf5to6server/tf5to6server.go:176 +0x225
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ReadResource(0x2f196c0?, {0x2f19688?, 0xc000c778c0?}, 0xc000e82e80)
	github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf6muxserver/mux_server_ReadResource.go:35 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0xc0008d3a40, {0x2f19688?, 0xc000c76f00?}, 0xc000c827e0)
	github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/tf6server/server.go:787 +0x48b
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0x2b4d160?, 0xc0008d3a40}, {0x2f19688, 0xc000c76f00}, 0xc000e9c780, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:467 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000d8d20, {0x2f19688, 0xc000c76e70}, {0x2f29e20, 0xc000a829c0}, 0xc000c7c5a0, 0xc000b578f0, 0x3ec5a08, 0x0)
	google.golang.org/grpc@v1.60.0/server.go:1372 +0xe03
google.golang.org/grpc.(*Server).handleStream(0xc0000d8d20, {0x2f29e20, 0xc000a829c0}, 0xc000c7c5a0)
	google.golang.org/grpc@v1.60.0/server.go:1783 +0xfec
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.60.0/server.go:1016 +0x59
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 54
	google.golang.org/grpc@v1.60.0/server.go:1027 +0x115

Error: The terraform-provider-snowflake_v0.83.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Steps to Reproduce

terraform import snowflake_schema.elt_metadata ELT_METADATA


### How much impact is this issue causing?

High

### Logs

_No response_

### Additional Information

_No response_

**Comment by peterspiro** [comment]
I hadn't familiarized myself with the format of the schema import statement.   The proper format worked:
```
terraform import snowflake_schema.elt_metadata "DB_NAME|ELT_METADATA"
```
