### ISSUE TITLE
Snowflake Provider failing to Load in Terraform Plan

### ISSUE THREAD

**Issue by rahulgoyal01** [Snowflake-Labs/terraform-provider-snowflake#2361]
I am running into the below error when I am trying to setup terraform for Snowflake CDP. 

```
Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ConfigureProvider call. The plugin logs may contain
│ more details.
╵
Stack trace from the terraform-provider-snowflake_v0.82.0 plugin:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15c59ac]
goroutine 26 [running]:
crypto/rsa.(*PrivateKey).Public(...)
	crypto/rsa/rsa.go:122
github.com/snowflakedb/gosnowflake.prepareJWTToken(0xc00086aa00)
	github.com/snowflakedb/gosnowflake@v1.7.1/auth.go:4[62](https://gitlab.veoliaes.com.au/veolia-edl/veolia-edl-terrasnow/-/jobs/113888#L62) +0x2c
github.com/snowflakedb/gosnowflake.createRequestBody(0xc0006f03c0, 0xc0005ca5f0?, {{0xc0006[64](https://gitlab.veoliaes.com.au/veolia-edl/veolia-edl-terrasnow/-/jobs/113888#L64)04f, 0x1c}, {0x1fd59e2, 0x5}, {0xc0005c3220, 0x8}, {0x1fe80ca, 0x9}}, ...)
	github.com/snowflakedb/gosnowflake@v1.7.1/auth.go:425 +0x435
github.com/snowflakedb/gosnowflake.authenticate.func1()
	github.com/snowflakedb/gosnowflake@v1.7.1/auth.go:336 +0x5e
github.com/snowflakedb/gosnowflake.(*retryHTTP).execute(0xc0009cfdb8)
	github.com/snowflakedb/gosnowflake@v1.7.1/retry.go:313 +0x1f7
github.com/snowflakedb/gosnowflake.postAuthRestful({0x2336b70?, 0x3339460?}, 0x19?, 0xc0005ca5c0?, 0x1c927a0?, 0x30?, 0xc000066400?, 0xc0001f4b40?)
	github.com/snowflakedb/gosnowflake@v1.7.1/restful.go:198 +0xef
github.com/snowflakedb/gosnowflake.postAuth({0x2336b70, 0x3339460}, 0xc000b01c70, 0x8?, 0xc0000[65](https://gitlab.veoliaes.com.au/veolia-edl/veolia-edl-terrasnow/-/jobs/113888#L65)a20, 0x70?, 0xc0000[66](https://gitlab.veoliaes.com.au/veolia-edl/veolia-edl-terrasnow/-/jobs/113888#L66)400?, 0xc000748460?)
	github.com/snowflakedb/gosnowflake@v1.7.1/auth.go:229 +0x36a
github.com/snowflakedb/gosnowflake.authenticate({0x2336b70, 0x3339460}, 0xc0006f03c0, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0})
	github.com/snowflakedb/gosnowflake@v1.7.1/auth.go:356 +0xfe8
github.com/snowflakedb/gosnowflake.authenticateWithConfig(0xc0006f03c0)
	github.com/snowflakedb/gosnowflake@v1.7.1/auth.go:547 +0x40b
github.com/snowflakedb/gosnowflake.SnowflakeDriver.OpenWithConfig({}, {_, _}, {{0xc000664009, 0x3}, {0xc000664000, 0x7}, {0xc000664000, 0x0}, {0x0, ...}, ...})
	github.com/snowflakedb/gosnowflake@v1.7.1/driver.go:43 +0x148
github.com/snowflakedb/gosnowflake.SnowflakeDriver.Open({}, {0xc000664000, 0xe8})
	github.com/snowflakedb/gosnowflake@v1.7.1/driver.go:26 +0x112
github.com/luna-duclos/instrumentedsql.dsnConnector.Connect(...)
	github.com/luna-duclos/instrumentedsql@v1.1.3/connector.go:53
github.com/luna-duclos/instrumentedsql.wrappedConnector.Connect({{{0x231eb60, 0x20e8ac8}, {0x2321a40, 0x3339460}, 0x0, 0x0}, {0x232ce30, 0xc0008d14c0}, 0xc0000d8f00}, {0x2336b70, ...})
	github.com/luna-duclos/instrumentedsql@v1.1.3/connector.go:33 +0x1ec
database/sql.(*DB).conn(0xc000b01ba0, {0x2336b70, 0x3339460}, 0x1)
	database/sql/sql.go:1387 +0x717
database/sql.(*DB).PingContext.func1(0x60?)
	database/sql/sql.go:850 +0x3a
database/sql.(*DB).retry(0xc0001f4960?, 0xc0009d0d38)
	database/sql/sql.go:1538 +0x42
database/sql.(*DB).PingContext(0xc000b01ba0, {0x2336b70?, 0x3339460})
	database/sql/sql.go:849 +0x94
database/sql.(*DB).Ping(...)
	database/sql/sql.go:8[67](https://gitlab.veoliaes.com.au/veolia-edl/veolia-edl-terrasnow/-/jobs/113888#L67)
github.com/jmoiron/sqlx.Connect({0x20166ac?, 0x16?}, {0xc000664000?, 0xc0000d8e40?})
	github.com/jmoiron/sqlx@v1.3.5/sqlx.go:642 +0x48
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk.NewClient(0x0?)
	github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk/client.go:137 +0x12f
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/provider.ConfigureProvider(0x1fd92ef?)
	github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/provider/provider.go:740 +0x1912
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Provider).Configure(0xc00065d4a0, {0x2336ba8, 0xc000aa3b00}, 0xc000ae0280)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/provider.go:296 +0x1b8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ConfigureProvider(0xc0006c0498, {0x2336ba8?, 0xc000aa2d80?}, 0xc000967de8)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/grpc_provider.go:607 +0x3a9
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ConfigureProvider({{0x234c180?, 0xc0006c0498?}}, {0x2336ba8?, 0xc000aa2d80?}, 0xc000967d88?)
	github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf5to6server/tf5to6server.go:80 +0x182
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ConfigureProvider(0xc000849180, {0x2336ba8?, 0xc000aa2a80?}, 0xc000aa2a50?)
	github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf6muxserver/mux_server_ConfigureProvider.go:28 +0x14f
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ConfigureProvider(0xc00096c000, {0x2336ba8?, 0xc000aa2270?}, 0xc0004d69c0)
	github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/tf6server/server.go:5[68](https://gitlab.veoliaes.com.au/veolia-edl/veolia-edl-terrasnow/-/jobs/113888#L68) +0x2ba
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ConfigureProvider_Handler({0x1f65f20?, 0xc00096c000}, {0x2336ba8, 0xc000aa2270}, 0xc000aec000, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:449 +0x1[69](https://gitlab.veoliaes.com.au/veolia-edl/veolia-edl-terrasnow/-/jobs/113888#L69)
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000c6d20, {0x2336ba8, 0xc000aa21e0}, {0x2347480, 0xc0007bc1a0}, 0xc000ae2000, 0xc000968810, 0x32f5b10, 0x0)
	google.golang.org/grpc@v1.60.0/server.go:13[72](https://gitlab.veoliaes.com.au/veolia-edl/veolia-edl-terrasnow/-/jobs/113888#L72) +0xe03
google.golang.org/grpc.(*Server).handleStream(0xc0000c6d20, {0x234[74](https://gitlab.veoliaes.com.au/veolia-edl/veolia-edl-terrasnow/-/jobs/113888#L74)80, 0xc0007bc1a0}, 0xc000ae2000)
	google.golang.org/grpc@v1.60.0/server.go:1[78](https://gitlab.veoliaes.com.au/veolia-edl/veolia-edl-terrasnow/-/jobs/113888#L78)3 +0xfec
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.60.0/server.go:1016 +0x59
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 21
	google.golang.org/grpc@v1.60.0/server.go:1027 +0x115
Error: The terraform-provider-snowflake_v0.[82](https://gitlab.veoliaes.com.au/veolia-edl/veolia-edl-terrasnow/-/jobs/113888#L82).0 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```
 
I am running terraform inside a container.  I have tried using older version of provider but getting the same error.

### Terraform Configuration

```terraform
terraform {
  required_providers {
    snowflake = {
      source = "Snowflake-Labs/snowflake"
      version = "0.82.0"
    }
  }
}

provider "snowflake" {
  role = "SYSADMIN"
  username = "User_Name"
}
```

### Expected Behavior

To generate Terraform Plan

### Actual Behavior

Plugin does not respond

### Steps to Reproduce

This is my compose file
```
version: "3.7"
services:
  terraform-utils:
    image: cmdlabs/terraform-utils:11.0.3
    env_file: .env
    environment:
      - ${NO_SSL}
      - SNOWFLAKE_ACCOUNT=Snowflake_account_name
      - SNOWFLAKE_AUTHENTICATOR=JWT
    entrypoint: ""
    volumes:
      - .:/work
      - ${SNOWFLAKE_CONFIG_PATH}:/root/.snowflake/config
      - ./init:/root/.ssh/
    working_dir: /work
```

Command to execute terraform plan
```
docker-compose run --rm terraform-utils sh -c 'terraform plan'
```

### How much impact is this issue causing?

High

**Comment by sfc-gh-asawicki** [comment]
Hey @rahulgoyal01. Thanks for reporting the issue.

The cause is most probably the same as described in https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/2317#issuecomment-1877254273. Please check if you are providing the private key the right way.

**Comment by sfc-gh-asawicki** [comment]
Hey @rahulgoyal01. Were you able to validate the proposed solution? Please let us know.

**Comment by rahulgoyal01** [comment]
Hi @sfc-gh-asawicki 
I was able to workout the issue. Thanks
