### ISSUE TITLE
[prerelease] panic with index out of range [1] when reading existing function

### ISSUE THREAD

**Issue by sonya** [Snowflake-Labs/terraform-provider-snowflake#2490]
### Terraform CLI and Provider Versions

Terraform v1.6.5
on darwin_arm64

Provider is built from current main branch (pre-0.86.0)

### Terraform Configuration

I can reproduce the problem with just this

```terraform
resource "snowflake_function" "my_function" {
  name            = "MY_FUNCTION"
  database        = "MY_DB"
  schema          = "MY_SCHEMA"
  return_type     = "VARCHAR"
  return_behavior = "IMMUTABLE"
  statement       = "SELECT PARAM"
  arguments {
    name = "PARAM"
    type = "VARCHAR"
  }
}
```

### Expected Behavior

Based on the steps to reproduce, the last step should result in `Your infrastructure matches the configuration.`

### Actual Behavior

`terraform plan` fails with the following stack trace:
```
Stack trace from the terraform-provider-snowflake plugin:

panic: runtime error: index out of range [1] with length 1

goroutine 3649 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk.NewSchemaObjectIdentifierFromFullyQualifiedName({0x1400026c230?, 0x0?})
    ~/code/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk/identifier_helpers.go:208 +0x344
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.ReadContextFunction({0x1065eef50, 0x14000898770}, 0x1400150a780, {0x1065aad00?, 0x14000e85790?})
    ~/code/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/function.go:515 +0x1f4
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x14000cb3260, {0x1065eeea8, 0x140006d6d20}, 0xd?, {0x1065aad00, 0x14000e85790})
    ~/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:795 +0xe8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x14000cb3260, {0x1065eeea8, 0x140006d6d20}, 0x1400160eea0, {0x1065aad00, 0x14000e85790})
    ~/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:1089 +0x430
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x14000cc84b0, {0x1065eeea8?, 0x140006d6bd0?}, 0x14000896b80)
    ~/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/grpc_provider.go:663 +0x3e4
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ReadResource({{0x106604458?, 0x14000cc84b0?}}, {0x1065eeea8?, 0x140006d6bd0?}, 0x14000896a00?)
    ~/go/pkg/mod/github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf5to6server/tf5to6server.go:176 +0x228
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ReadResource(0x1065eeee0?, {0x1065eeea8?, 0x140006d68d0?}, 0x14000896a00)
    ~/go/pkg/mod/github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf6muxserver/mux_server_ReadResource.go:35 +0x184
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0x14000b34820, {0x1065eeea8?, 0x14000f17ec0?}, 0x1400108c300)
    ~/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/tf6server/server.go:787 +0x390
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0x106559360?, 0x14000b34820}, {0x1065eeea8, 0x14000f17ec0}, 0x1400150a500, 0x0)
    ~/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:467 +0x164
google.golang.org/grpc.(*Server).processUnaryRPC(0x140000ded20, {0x1065eeea8, 0x14000f17e30}, {0x1065ffa60, 0x140001036c0}, 0x14000dcac60, 0x14000d93710, 0x1073dbb88, 0x0)
    ~/go/pkg/mod/google.golang.org/grpc@v1.60.0/server.go:1372 +0xb8c
google.golang.org/grpc.(*Server).handleStream(0x140000ded20, {0x1065ffa60, 0x140001036c0}, 0x14000dcac60)
    ~/go/pkg/mod/google.golang.org/grpc@v1.60.0/server.go:1783 +0xc44
google.golang.org/grpc.(*Server).serveStreams.func2.1()
    ~/go/pkg/mod/google.golang.org/grpc@v1.60.0/server.go:1016 +0x5c
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 43
    ~/go/pkg/mod/google.golang.org/grpc@v1.60.0/server.go:1027 +0x138
```

### Steps to Reproduce

1. Install a currently released version of the provider (I started from 0.79.0)
2. Deploy the above configuration to create a function
3. Run `terraform plan`. You should see `Your infrastructure matches the configuration.`.
4. Install the 0.86.0 version of the provider (I built this off the current `main` branch)
5. Run `terraform plan`.

### How much impact is this issue causing?

Medium

### Additional Information

I am filing this issue about a pre-release version so it isn't a real issue yet. I am flagging in the off-chance that it hasn't already been noticed and ends up being released.

**Comment by sfc-gh-asawicki** [comment]
Hey @sonya. Thanks for bringing this to our attention.

I have fixed the behavior in #2503 by adding a state upgrader. We will release it today but you can check it prerelease if you want :)
