### ISSUE TITLE
Index out of range error 

### ISSUE THREAD

**Issue by javabudd** [Snowflake-Labs/terraform-provider-snowflake#2739]
### Terraform CLI and Provider Versions

Terraform 1.8.1
Snowflake-labs/snowflake 0.66.1 (happens on 0.69.0 as well)

### Terraform Configuration

```terraform
N/A
```

### Expected Behavior
`terraform plan` succeeds

### Actual Behavior

Plan crashes with the following error:

```
Stack trace from the terraform-provider-snowflake_v0.66.1 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 5771 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/snowflake.(*ViewSelectStatementExtractor).consumeToken(0xc000c351d0, {0x15f1a7b, 0x6})
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/snowflake/parser.go:97 +0x148
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/snowflake.(*ViewSelectStatementExtractor).Extract(0xc000c351d0)
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/snowflake/parser.go:30 +0x9b
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.ReadView(0xc00018f580, {0x15d1380?, 0xc00093ab60})
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/view.go:251 +0x5a6
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x18d3960?, {0x18d3960?, 0xc00149bc50?}, 0xd?, {0x15d1380?, 0xc00093ab60?})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:712 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000920000, {0x18d3960, 0xc00149bc50}, 0xc0012db790, {0x15d1380, 0xc00093ab60})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0006e9710, {0x18d3960?, 0xc00149bb30?}, 0xc000e6ed40)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:613 +0x4a5
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0006e6c80, {0x18d3960?, 0xc00149b140?}, 0xc001330600)
github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:748 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x1593ec0?, 0xc0006e6c80}, {0x18d3960, 0xc00149b140}, 0xc00119a850, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000032960, {0x18da860, 0xc000102b60}, 0xc000fd2fc0, 0xc0007c61e0, 0x2287490, 0x0)
google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc000032960, {0x18da860, 0xc000102b60}, 0xc000fd2fc0, 0x0)
google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

Error: The terraform-provider-snowflake_v0.66.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Steps to Reproduce

Steps to reproduce are unknown ATM. This started happening randomly today after no changes to our Snowflake or Terraform configurations.

### How much impact is this issue causing?

High

**Comment by sfc-gh-asawicki** [comment]
Hey @javabudd. Thanks for reaching out to us.

You are using a really old provider version. Keep in mind that we are currently in an experimental phase (https://github.com/Snowflake-Labs/terraform-provider-snowflake?tab=readme-ov-file#snowflake-terraform-provider) and we do not provide backward bug fixes.

A similar problem was described and fixed in https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/2640 (it was about secure views, so I am not sure if this is your case too). I can't see any Snowflake BCR that could affected the behavior. I have just run our acceptance tests in the newest version and got no errors (any failures could indicate changes on Snowflake side).

Please bump to the newest version and verify if the bug persists (please check the https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md#migration-guide while doing it).

**Comment by javabudd** [comment]
I was able to reproduce the issue by creating a secured view in terraform and then changing ownership of that view to account admin (a role that terraform does not have access to). Any updates to that view afterwards fail silently due to not being able to retrieve information about the view.
