### ISSUE TITLE
snowflake_table_column_masking_policy_application 

### ISSUE THREAD

**Issue by carmas** [Snowflake-Labs/terraform-provider-snowflake#2754]
### Terraform CLI and Provider Versions

Terraform v1.8.2
on darwin_arm64
+ provider registry.terraform.io/snowflake-labs/snowflake v0.85.0

### Terraform Configuration

```terraform
###############################
# define mask for account number
###############################
module "P1" {
  source       = "../../modules/snowflake/masking-policy"
  policy_name  = "P1.account_number"
  column_name  = "ACCOUNT_NUMBER"
  comment      = "customer account"
  db_name      = var.db_name
  schema_name  = var.schema_name
  masked_roles = var.masked_roles
}

# apply mask to column

module "P1_ACCOUNT" {
  source      = "../../modules/snowflake/apply-masking-policy"
  table_name  = "${var.db_name}.${var.schema_name}.ACCOUNT"
  policy_name = module.P1.id
  column_name = "ACCOUNT_NUMBER"
}



###############################
# define mask for created date
################################
module "P2" {
  source       = "../../modules/snowflake/masking-policy"
  policy_name  = "P2.created_at"
  column_name  = "CREATED_AT"
  column_type  = "TIMESTAMP_NTZ"
  comment      = "account creation date"
  db_name      = var.db_name
  schema_name  = var.schema_name
  masked_roles = var.masked_roles
}

module "P2_CREATED_AT" {
  source      = "../../modules/snowflake/apply-masking-policy"
  table_name  = "${var.db_name}.${var.schema_name}.ACCOUNT"
  policy_name = module.P2.id
  column_name = "CREATED_AT"
}
```

### Expected Behavior

Expecting terraform apply to apply 

### Actual Behavior

Terraform will perform the following actions:

  # module.P1_ACCOUNT.snowflake_table_column_masking_policy_application.mask_application will be created
  + resource "snowflake_table_column_masking_policy_application" "mask_application" {
      + column         = "ACCOUNT_NUMBER"
      + id             = (known after apply)
      + masking_policy = "STAGING_XMIN|CORE_SCHEMA|P1.account_number"
      + table          = "STAGING_XMIN.CORE_SCHEMA.ACCOUNT"
    }

  # module.P2_CREATED_AT.snowflake_table_column_masking_policy_application.mask_application will be created
  + resource "snowflake_table_column_masking_policy_application" "mask_application" {
      + column         = "CREATED_AT"
      + id             = (known after apply)
      + masking_policy = "STAGING_XMIN|CORE_SCHEMA|P2.created_at"
      + table          = "STAGING_XMIN.CORE_SCHEMA.ACCOUNT"
    }

Plan: 2 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.P1_ACCOUNT.snowflake_table_column_masking_policy_application.mask_application: Creating...
module.P2_CREATED_AT.snowflake_table_column_masking_policy_application.mask_application: Creating...
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-snowflake_v0.85.0 plugin:

panic: runtime error: index out of range [2] with length 2

goroutine 61 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/snowflake.SchemaObjectIdentifierFromQualifiedName({0x140001c2870?, 0x103adf987?})
	github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/snowflake/identifier.go:58 +0x174
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.CreateTableColumnMaskingPolicyApplication(0x0?, {0x104293940?, 0x1400088a9c0})
	github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/table_column_masking_policy_application.go:54 +0xc8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1042d7248?, {0x1042d7248?, 0x14000a27ad0?}, 0xd?, {0x104293940?, 0x1400088a9c0?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:766 +0x134
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x14000c73180, {0x1042d7248, 0x14000a27ad0}, 0x140009b7110, 0x14000aef080, {0x104293940, 0x1400088a9c0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:909 +0x86c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x14000997de8, {0x1042d7248?, 0x14000a27920?}, 0x14000718960)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/grpc_provider.go:1074 +0xb08
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ApplyResourceChange({{0x1042ec718?, 0x14000997de8?}}, {0x1042d7248, 0x14000a27920}, 0x0?)
	github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf5to6server/tf5to6server.go:37 +0x58
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ApplyResourceChange(0x1042d7280?, {0x1042d7248?, 0x14000a27620?}, 0x14000718910)
	github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf6muxserver/mux_server_ApplyResourceChange.go:36 +0x184
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0x1400099e0a0, {0x1042d7248?, 0x14000a26c30?}, 0x140009dd030)
	github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/tf6server/server.go:857 +0x3c0
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x104241ee0?, 0x1400099e0a0}, {0x1042d7248, 0x14000a26c30}, 0x14000aee680, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:503 +0x164
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000142d20, {0x1042d7248, 0x14000ac4f90}, {0x1042e7d20, 0x14000a03380}, 0x14000aca5a0, 0x14000c7bb90, 0x105187af8, 0x0)
	google.golang.org/grpc@v1.60.0/server.go:1372 +0xb8c
google.golang.org/grpc.(*Server).handleStream(0x14000142d20, {0x1042e7d20, 0x14000a03380}, 0x14000aca5a0)
	google.golang.org/grpc@v1.60.0/server.go:1783 +0xc4c
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.60.0/server.go:1016 +0x5c
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 29
	google.golang.org/grpc@v1.60.0/server.go:1027 +0x138
panic: runtime error: index out of range [2] with length 2

goroutine 60 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/snowflake.SchemaObjectIdentifierFromQualifiedName({0x140009e7a10?, 0x103adf987?})
	github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/snowflake/identifier.go:58 +0x174
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.CreateTableColumnMaskingPolicyApplication(0x0?, {0x104293940?, 0x1400088a9c0})
	github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/table_column_masking_policy_application.go:54 +0xc8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1042d7248?, {0x1042d7248?, 0x14000b20b10?}, 0xd?, {0x104293940?, 0x1400088a9c0?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:766 +0x134
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x14000c73180, {0x1042d7248, 0x14000b20b10}, 0x140008495f0, 0x14000866880, {0x104293940, 0x1400088a9c0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:909 +0x86c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x14000997de8, {0x1042d7248?, 0x14000b20960?}, 0x14000b32050)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/grpc_provider.go:1074 +0xb08
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ApplyResourceChange({{0x1042ec718?, 0x14000997de8?}}, {0x1042d7248, 0x14000b20960}, 0x0?)
	github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf5to6server/tf5to6server.go:37 +0x58
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ApplyResourceChange(0x1042d7280?, {0x1042d7248?, 0x14000b20660?}, 0x14000b32000)
	github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf6muxserver/mux_server_ApplyResourceChange.go:36 +0x184
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0x1400099e0a0, {0x1042d7248?, 0x1400084fe30?}, 0x14000b02cb0)
	github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/tf6server/server.go:857 +0x3c0
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x104241ee0?, 0x1400099e0a0}, {0x1042d7248, 0x1400084fe30}, 0x14000866600, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:503 +0x164
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000142d20, {0x1042d7248, 0x14000ac5020}, {0x1042e7d20, 0x14000a03380}, 0x14000aca480, 0x14000c7bb90, 0x105187af8, 0x0)
	google.golang.org/grpc@v1.60.0/server.go:1372 +0xb8c
google.golang.org/grpc.(*Server).handleStream(0x14000142d20, {0x1042e7d20, 0x14000a03380}, 0x14000aca480)
	google.golang.org/grpc@v1.60.0/server.go:1783 +0xc4c
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.60.0/server.go:1016 +0x5c
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 29
	google.golang.org/grpc@v1.60.0/server.go:1027 +0x138

Error: The terraform-provider-snowflake_v0.85.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

High

### Additional Information

The plugin crashes specifically when applying a policy to a column.
We are able to create policies with a module. 

The plugin crashes when attempt to apply an already defined/created policy to a column.
The error we get is not related to a malformed config, the plugin just crashes, miserably:

```
module.P1_ACCOUNT.snowflake_table_column_masking_policy_application.mask_application: Creating...
module.P2_CREATED_AT.snowflake_table_column_masking_policy_application.mask_application: Creating...
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
......
```

 See full error output above (Actual Behavior section)

**Comment by sfc-gh-asawicki** [comment]
Hey @carmas. Thanks for reaching out to us.

According to our docs, `masking_policy` should be a fully qualified name (https://registry.terraform.io/providers/Snowflake-Labs/snowflake/0.85.0/docs/resources/table_column_masking_policy_application#masking_policy) and from the logs provided you are using `STAGING_XMIN|CORE_SCHEMA|P2.created_at` that is not the right format.

**Comment by carmas** [comment]
I will test it in the morning Pacific Time, great hint
