### ISSUE TITLE
[Bug]: Error: The terraform-provider-snowflake_v0.89.0 plugin crashed!

### ISSUE THREAD

**Issue by Ghaitharar** [Snowflake-Labs/terraform-provider-snowflake#2779]
### Terraform CLI Version

0.89.0

### Terraform Provider Version

0.89.0

### Terraform Configuration

```terraform
Stack trace from the terraform-provider-snowflake_v0.89.0 plugin:

panic: interface conversion: sdk.ObjectIdentifier is sdk.AccountObjectIdentifier, not sdk.DatabaseObjectIdentifier

goroutine 77 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.ReadSchema(0xc000b26880, {0x1cd55c0?, 0xc00008a778?})
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/schema.go:108 +0x899
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x24556c8?, {0x24556c8?, 0xc000b4f920?}, 0xd?, {0x1cd55c0?, 0xc00008a778?})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:783 +0x163
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000a809a0, {0x24556c8, 0xc000b4f920}, 0xc000a8f1e0, {0x1cd55c0, 0xc00008a778})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:1089 +0x552
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0007df650, {0x24556c8?, 0xc000c06240?}, 0xc000d06c80)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/grpc_provider.go:663 +0x48a
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ReadResource({{0x246b560?, 0xc0007df650?}}, {0x24556c8?, 0xc000c06240?}, 0xc001187380?)
github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf5to6server/tf5to6server.go:176 +0x225
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ReadResource(0x2455700?, {0x24556c8?, 0xc000883e60?}, 0xc001187380)
github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf6muxserver/mux_server_ReadResource.go:35 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0xc0007fcbe0, {0x24556c8?, 0xc000883680?}, 0xc0011a4ae0)
github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/tf6server/server.go:787 +0x48b
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0x20288a0?, 0xc0007fcbe0}, {0x24556c8, 0xc000883680}, 0xc000737800, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:467 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000e8d20, {0x24556c8, 0xc0008835f0}, {0x24667e0, 0xc000b84340}, 0xc000a437a0, 0xc000b154d0, 0x345f028, 0x0)
google.golang.org/grpc@v1.60.0/server.go:1372 +0xe03
google.golang.org/grpc.(*Server).handleStream(0xc0000e8d20, {0x24667e0, 0xc000b84340}, 0xc000a437a0)
google.golang.org/grpc@v1.60.0/server.go:1783 +0xfec
google.golang.org/grpc.(*Server).serveStreams.func2.1()
google.golang.org/grpc@v1.60.0/server.go:1016 +0x59
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 42
google.golang.org/grpc@v1.60.0/server.go:1027 +0x115
panic: interface conversion: sdk.ObjectIdentifier is sdk.AccountObjectIdentifier, not sdk.DatabaseObjectIdentifier

goroutine 76 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.ReadSchema(0xc000cce180, {0x1cd55c0?, 0xc00008a778?})
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/schema.go:108 +0x899
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x24556c8?, {0x24556c8?, 0xc000c904b0?}, 0xd?, {0x1cd55c0?, 0xc00008a778?})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:783 +0x163
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000a809a0, {0x24556c8, 0xc000c904b0}, 0xc000cae340, {0x1cd55c0, 0xc00008a778})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:1089 +0x552
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0007df650, {0x24556c8?, 0xc000c90360?}, 0xc000a261c0)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/grpc_provider.go:663 +0x48a
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ReadResource({{0x246b560?, 0xc0007df650?}}, {0x24556c8?, 0xc000c90360?}, 0xc000a26000?)
github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf5to6server/tf5to6server.go:176 +0x225
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ReadResource(0x2455700?, {0x24556c8?, 0xc000c90060?}, 0xc000a26000)
github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf6muxserver/mux_server_ReadResource.go:35 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0xc0007fcbe0, {0x24556c8?, 0xc000f21770?}, 0xc000bd0780)
github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/tf6server/server.go:787 +0x48b
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0x20288a0?, 0xc0007fcbe0}, {0x24556c8, 0xc000f21770}, 0xc000057100, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:467 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000e8d20, {0x24556c8, 0xc000f216e0}, {0x24667e0, 0xc000b84340}, 0xc000a43680, 0xc000b154d0, 0x345f028, 0x0)
google.golang.org/grpc@v1.60.0/server.go:1372 +0xe03
google.golang.org/grpc.(*Server).handleStream(0xc0000e8d20, {0x24667e0, 0xc000b84340}, 0xc000a43680)
google.golang.org/grpc@v1.60.0/server.go:1783 +0xfec
google.golang.org/grpc.(*Server).serveStreams.func2.1()
google.golang.org/grpc@v1.60.0/server.go:1016 +0x59
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 42
google.golang.org/grpc@v1.60.0/server.go:1027 +0x115

Error: The terraform-provider-snowflake_v0.89.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Category

category:import

### Expected Behavior

plan and apply with no issues.

### Actual Behavior

The plugin crushed.

### Steps to Reproduce

variable "DEV_schema_map" {
  description = "List of GEs"
  type        = map
  default = { for SC in ["DE_1", "DE_2", "DE_3", "DE_4", "DE_5", "DE_6"] : SC => SC}
}

resource "snowflake_schema" "DEV_schemas" {
  for_each = var.DEV_schema_map
  name = each.value
  database = snowflake_database.DEV.name
}

import {
  for_each = var.DEV_schema_map
  id = each.value
  to = snowflake_schema.DEV_schemas[each.value]
}

### How much impact is this issue causing?

Medium

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-asawicki** [comment]
Hey @Ghaitharar. Thanks for reaching out to us.

Your import statement is incorrect: https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/schema#import. You have to use qualified name and you are only using the schema name without the db.

**Comment by sfc-gh-asawicki** [comment]
Hey @Ghaitharar. Can you confirm that the proposed solution worked?

**Comment by sfc-gh-asawicki** [comment]
Closing due to inactivity.

**Comment by pose** [comment]
For anyone that runs into this issue, it seems that the provider expects identifiers `|`-separated (instead of `.`-separated). For example:

```
# format is database name | schema name | stage name
terraform import snowflake_stage.example 'dbName|schemaName|stageName'
```

I believe that `panic`ing in these scenarios is a bit too extreme. A validation could be introduced to make sure users are `|`-separating and warn users if they are `.`-separating. @sfc-gh-asawicki  I would be more than happy to open a ticket (if my assumptions are correct).

**Comment by sfc-gh-asawicki** [comment]
Hey @pose, this is the old provider version. Please check:
- https://github.com/snowflakedb/terraform-provider-snowflake/blob/main/docs/guides/identifiers_rework_design_decisions.md
- https://github.com/snowflakedb/terraform-provider-snowflake/blob/main/KNOWN_ISSUES.md#incorrect-identifier-index-out-of-bounds-even-with-the-old-error-message
- https://github.com/snowflakedb/terraform-provider-snowflake/blob/main/KNOWN_ISSUES.md#incorrect-identifier-type-panic-interface-conversion

**Comment by pose** [comment]
Hi @sfc-gh-asawicki, thanks for replying. I am able to reproduce the issue with `terraform-provider-snowflake_v2.10.0`. Please see the following logs:

```
$  terraform import snowflake_stage.test_import_stage 'MYDB.PUBLIC.MYTESTSTAGE'
snowflake_stage.test_import_stage: Preparing import... [id=MYDB.PUBLIC.MYTESTSTAGE]
snowflake_stage.test_import_stage: Refreshing state... [id=MYDB.PUBLIC.MYTESTSTAGE]

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).ReadResource request was cancelled.
╵

Stack trace from the terraform-provider-snowflake_v2.10.0 plugin:

panic: interface conversion: sdk.ObjectIdentifier is sdk.AccountObjectIdentifier, not sdk.SchemaObjectIdentifier

goroutine 41 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.ReadStage({0x10495a2d8, 0x14000e09d10}, 0x14000750ab0, {0x1044364a0?, 0x14000495c00?})
	github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/stage.go:183 +0x130c
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.Stage.TrackingReadWrapper.func5({0x10495a380, 0x14000e28700}, 0x14000750ab0, {0x1044364a0, 0x14000495c00})
	github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/common.go:139 +0xf0
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.Stage.PreviewFeatureReadContextWrapper.func6({0x10495a380, 0x14000e28700}, 0x14000750ab0, {0x1044364a0, 0x14000495c00})
	github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/common.go:190 +0x84
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x1400073e600, {0x10495a2d8, 0x14000e090b0}, 0x14000750ab0, {0x1044364a0, 0x14000495c00})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.37.0/helper/schema/resource.go:866 +0xe4
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x1400073e600, {0x10495a2d8, 0x14000e090b0}, 0x14000e9e680, {0x1044364a0, 0x14000495c00})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.37.0/helper/schema/resource.go:1162 +0x3f8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x140008172c0, {0x10495a2d8?, 0x14000e08f90?}, 0x140002c6730)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.37.0/helper/schema/grpc_provider.go:908 +0x9c8
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ReadResource({{0x1049946e0?, 0x140008172c0?}}, {0x10495a2d8, 0x14000e08f90}, 0x0?)
	github.com/hashicorp/terraform-plugin-mux@v0.20.0/tf5to6server/tf5to6server.go:187 +0x58
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ReadResource(0x14000181900, {0x10495a2d8?, 0x14000e08cc0?}, 0x140002c66e0)
	github.com/hashicorp/terraform-plugin-mux@v0.20.0/tf6muxserver/mux_server_ReadResource.go:35 +0x184
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0x140004a2960, {0x10495a2d8?, 0x14000e081e0?}, 0x14000e28070)
	github.com/hashicorp/terraform-plugin-go@v0.28.0/tfprotov6/tf6server/server.go:860 +0x21c
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0x1048c2900, 0x140004a2960}, {0x10495a2d8, 0x14000e081e0}, 0x14000180500, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.28.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:651 +0x1c0
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400081a200, {0x10495a2d8, 0x14000e08150}, 0x14000b9e000, 0x1400086ed50, 0x105c9bdb8, 0x0)
	google.golang.org/grpc@v1.73.0/server.go:1405 +0xca8
google.golang.org/grpc.(*Server).handleStream(0x1400081a200, {0x10495d610, 0x140008c6000}, 0x14000b9e000)
	google.golang.org/grpc@v1.73.0/server.go:1815 +0x910
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.73.0/server.go:1035 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 53
	google.golang.org/grpc@v1.73.0/server.go:1046 +0x13c

Error: The terraform-provider-snowflake_v2.10.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

This is how I am configuring the Snowflake version on my `main.tf`:

```ts
terraform {
  required_providers {
    snowflake = {
      source  = "snowflakedb/snowflake"
      version = ">= 2.0.0"
    }
  }
}
```

Please do let me know if I am doing something wrong. Thanks!

**Comment by sfc-gh-asawicki** [comment]
Hey:
- the `|` are needed in the stage resource as documented: https://registry.terraform.io/providers/snowflakedb/snowflake/latest/docs/resources/stage#import
- The stage resource is a preview feature - it uses the old identifier handling (check references), and it was not adjusted to the identifier changes that I referenced. It will be fixed with the stabilization of the stage resource.
- The error handling for the stable resources is different; that's why the suggested warnings and validations are not needed.

**Comment by pose** [comment]
Ah, I got it now. Makes sense. I'm no expert in Snowflake so I appreciate the guidance here. Thanks again! 🙏
