### ISSUE TITLE
[Bug]: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by RichYoungHaven** [Snowflake-Labs/terraform-provider-snowflake#2823]
### Terraform CLI Version

1.5.7

### Terraform Provider Version

0.91.0

### Terraform Configuration

```terraform
I have two providers in my code. A standard terrafrom one and a snowflake one. Ive added an extra default_tag to the standard terrafrom provider tags.
When creating a plan i get the following issue. 

`panic: runtime error: invalid memory address or nil pointer dereference`

There aren't actually any changes being deployed to snowflake, just tags in associated resources in our cloud :
```

### Category

category:resource

### Expected Behavior

Plan builds

### Actual Behavior

```terraform
Error: Plugin did not respond

The plugin encountered an error, and failed to respond to the
plugin6.(*GRPCProvider).ConfigureProvider call. The plugin logs may contain
more details.

Stack trace from the terraform-provider-snowflake_v0.91.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x140320c]

goroutine 49 [running]:
crypto/rsa.(*PrivateKey).Public(...)
	crypto/rsa/rsa.go:122
github.com/snowflakedb/gosnowflake.prepareJWTToken(0xc00096aa00)
	github.com/snowflakedb/gosnowflake@v1.10.0/auth.go:476 +0x2c
github.com/snowflakedb/gosnowflake.createRequestBody(0xc0008ba240, 0xc000536880?, {{0xc000528159, 0x1c}, {0x206fe36, 0x5}, {0xc000510e08, 0x8}, {0x2082a8c, 0x9}, ...}, ...)
	github.com/snowflakedb/gosnowflake@v1.10.0/auth.go:439 +0x479
github.com/snowflakedb/gosnowflake.authenticate.func1()
	github.com/snowflakedb/gosnowflake@v1.10.0/auth.go:339 +0x65
github.com/snowflakedb/gosnowflake.(*retryHTTP).execute(0xc000a0dce0)
	github.com/snowflakedb/gosnowflake@v1.10.0/retry.go:310 +0x20a
github.com/snowflakedb/gosnowflake.postAuthRestful({0x242ef80?, 0x3417cc0?}, 0x208dfc4?, 0xc0008e8dd0?, 0xc000a0dec8?, 0xc000a0deb0?, 0xc000a0de50?, 0x418688?)
	github.com/snowflakedb/gosnowflake@v1.10.0/restful.go:199 +0xef
github.com/snowflakedb/gosnowflake.postAuth({0x242ef80, 0x3417cc0}, 0xc000926d00, 0x8?, 0xc0008e8dd0, 0xffffffffffffff9c?, 0xc0008a65a0?, 0xc000a0e028?)
	github.com/snowflakedb/gosnowflake@v1.10.0/auth.go:231 +0x372
github.com/snowflakedb/gosnowflake.authenticate({0x242ef80, 0x3417cc0}, 0xc0008ba240, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0})
	github.com/snowflakedb/gosnowflake@v1.10.0/auth.go:359 +0x11e8
github.com/snowflakedb/gosnowflake.authenticateWithConfig(0xc0008ba240)
	github.com/snowflakedb/gosnowflake@v1.10.0/auth.go:553 +0x33e
github.com/snowflakedb/gosnowflake.SnowflakeDriver.OpenWithConfig({}, {_, _}, {{0xc000528120, 0x7}, {0xc000528100, 0x1e}, {0xc000528100, 0x0}, {0x0, ...}, ...})
	github.com/snowflakedb/gosnowflake@v1.10.0/driver.go:44 +0x165
github.com/snowflakedb/gosnowflake.SnowflakeDriver.Open({}, {0xc000528100, 0xf7})
	github.com/snowflakedb/gosnowflake@v1.10.0/driver.go:27 +0x106
github.com/luna-duclos/instrumentedsql.dsnConnector.Connect(...)
	github.com/luna-duclos/instrumentedsql@v1.1.3/connector.go:53
github.com/luna-duclos/instrumentedsql.wrappedConnector.Connect({{{0x2415e60, 0x218dae0}, {0x2418a00, 0x3417cc0}, 0x0, 0x0}, {0x241e918, 0xc0000bd600}, 0xc000532dc0}, {0x242ef80, ...})
	github.com/luna-duclos/instrumentedsql@v1.1.3/connector.go:33 +0x1ec
database/sql.(*DB).conn(0xc000926a90, {0x242ef80, 0x3417cc0}, 0x1)
	database/sql/sql.go:1387 +0x717
database/sql.(*DB).PingContext.func1(0x60?)
	database/sql/sql.go:850 +0x3a
database/sql.(*DB).retry(0xc00093e960?, 0xc000a0ee40)
	database/sql/sql.go:1538 +0x42
database/sql.(*DB).PingContext(0xc000926a90, {0x242ef80?, 0x3417cc0})
	database/sql/sql.go:849 +0x94
database/sql.(*DB).Ping(...)
	database/sql/sql.go:867
github.com/jmoiron/sqlx.Connect({0x20b10eb?, 0x16?}, {0xc000528100?, 0xc000532d80?})
	github.com/jmoiron/sqlx@v1.3.5/sqlx.go:642 +0x48
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk.NewClient(0x0?)
	github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk/client.go:151 +0x12f
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/provider.ConfigureProvider(0x20735ae?)
	github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/provider/provider.go:788 +0x19d2
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Provider).Configure(0xc0007e25a0, {0x242efb8, 0xc000891b00}, 0xc000894280)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/provider.go:296 +0x1b8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ConfigureProvider(0xc0000103d8, {0x242efb8?, 0xc000890d80?}, 0xc0007042d0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/grpc_provider.go:611 +0x3a9
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ConfigureProvider({{0x2445c40?, 0xc0000103d8?}}, {0x242efb8?, 0xc000890d80?}, 0xc000704270?)
	github.com/hashicorp/terraform-plugin-mux@v0.15.0/tf5to6server/tf5to6server.go:86 +0x182
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ConfigureProvider(0xc000b84000, {0x242efb8?, 0xc000890a80?}, 0xc000890a50?)
	github.com/hashicorp/terraform-plugin-mux@v0.15.0/tf6muxserver/mux_server_ConfigureProvider.go:28 +0x14f
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ConfigureProvider(0xc0007e61e0, {0x242efb8?, 0xc000890240?}, 0xc000532300)
	github.com/hashicorp/terraform-plugin-go@v0.22.2/tfprotov6/tf6server/server.go:558 +0x2db
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ConfigureProvider_Handler({0x1ffb1e0?, 0xc0007e61e0}, {0x242efb8, 0xc000890240}, 0xc0005d4080, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.22.2/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:464 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0009ae200, {0x242efb8, 0xc0008901b0}, {0x2440e00, 0xc0005c0180}, 0xc0008c2000, 0xc000101ef0, 0x33d3930, 0x0)
	google.golang.org/grpc@v1.63.2/server.go:1369 +0xe23
google.golang.org/grpc.(*Server).handleStream(0xc0009ae200, {0x2440e00, 0xc0005c0180}, 0xc0008c2000)
	google.golang.org/grpc@v1.63.2/server.go:1780 +0x1016
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 20
	google.golang.org/grpc@v1.63.2/server.go:1030 +0x135

Error: The terraform-provider-snowflake_v0.91.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Steps to Reproduce

As Above

### How much impact is this issue causing?

High

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by RichYoungHaven** [comment]
The provider is configured like this:
```terraform
terraform {
  backend "s3" {}

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.48"

    }
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "0.91.0"
    }
  }
}

provider "aws" {
  profile = var.aws_profile
  region  = var.aws_region
  default_tags {
    tags = local.default_tags
  }
}
```
if i remove the tag i added to ```default_tags``` the plan builds fine. i add a new tag and it doesnt

**Comment by sfc-gh-asawicki** [comment]
Hey @RichYoungHaven. Thanks for reaching out to us.

This looks similar to several other reported issues (e.g., https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/2645 and https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/2765). Please check your private key configuration.

**Comment by RichYoungHaven** [comment]
It does look similiar @sfc-gh-asawicki but if i remove the tag the plan builds fine. So it seems me adding a `map-migrated` tag to the provider default tags is the cause of the issue. There is a workaround (put an override_tf in the project with the provider but without that tag) but it would be good if we could identify the underlying cause

**Comment by sfc-gh-asawicki** [comment]
@RichYoungHaven but you are adding it to the AWS provider, not to the Snowflake provider, so I don't think this is the issue with our provider.

I don't know how you use it underneath and if you use it to set up the Snowflake provider but as I said, the problem is with the improper private key passed to our provider.

**Comment by RichYoungHaven** [comment]
how does the key work without that tag then? Little confused...... shouldn't the key either work or not work?

**Comment by sfc-gh-asawicki** [comment]
I don't know what your configuration looks like, and you did not share how the private key is set. But as I said, you are altering other provider's config, so:
- you may be using it to set the key in our provider or it messes up your setup for the snowflake provider (can't say not knowing your setup)
- something changed externally and it's not connected with the `default_tags` at all

**Comment by RichYoungHaven** [comment]
This is how the key is used (starred out sensitive data):
```hcl
provider "snowflake" {
  account                = "*****.eu-west-1"              # required if not using profile. Can also be set via SNOWFLAKE_ACCOUNT env var
  user                   = "*****.terraform.transform.dev" # required if not using profile or token. Can also be set via SNOWFLAKE_USER env var
  private_key            = data.aws_ssm_parameter.snowflake_private_key.value
  private_key_passphrase = data.aws_ssm_parameter.snowflake_passphrase.value
  authenticator          = "JWT"
  role                   = "*****_terraform_transform_dev"
}
```
The key is set with a data source so shouldnt be effected by a provider tag. the only external change is adding the extra tag to the local.default_tags.

**Comment by sfc-gh-asawicki** [comment]
Thanks for sharing the config @RichYoungHaven. So what I see here:
- `data.aws_ssm_parameter.snowflake_private_key.value` is not returning the proper private key when you set `default_tags` on the AWS provider - as I pointed out earlier, this is the behavior of the AWS provider, not ours;
- you are setting the provider based on the output of datasource in another provider - AFAIK, this is not the correct setup of the provider in general, please check my answer and referenced links here: https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/2127#issuecomment-1766576750

**Comment by RichYoungHaven** [comment]
that cant be the case as there are other tags already being set (starred for privacy):

![image](https://github.com/Snowflake-Labs/terraform-provider-snowflake/assets/111752838/c1980259-076a-4292-ba85-e546aa8d89c8)
Not sure it its updating the list of tags that is causing an issue with your provider? The datasource has been working perfectly fine.

**Comment by RichYoungHaven** [comment]
Seems like we are going around in circles on this. I tested your approach and as expected it had the same results in that it doesn't work. The data source looks at an exiting resource and always pulls the same value back regardless of the extra tag being there or not. As such i'm leaving it with my override workaround.

**Comment by sfc-gh-asawicki** [comment]
@RichYoungHaven, setting the `private_key` is one of the most commonly used ways to configure our provider. Since there is no crowd commenting that this provider configuration method is broken, this raises the possibility that the configuration is incorrect (it results in the same error as in other issues resulting from the incorrect configuration).

I have linked you the comment referencing the terraform documentation (this one https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/2127#issuecomment-1766576750) which explains why you may encounter problems like this with your current setup. From the [Terraform docs](https://developer.hashicorp.com/terraform/language/providers/configuration) on provider configuration:

> You can use [expressions](https://developer.hashicorp.com/terraform/language/expressions) in the values of these configuration arguments, but can only reference values that are known before the configuration is applied. This means you can safely reference input variables, but not attributes exported by resources (with an exception for resource arguments that are specified directly in the configuration).

Setting both `private_key` and `private_key_passphrase` correctly and explicitly (not the datasource returned values) is the widely used method, so maybe you did not set them correctly while checking my suggestion.

**Comment by sfc-gh-asawicki** [comment]
Closing due to inactivity.
