### ISSUE TITLE
[Bug]: Error: The terraform-provider-snowflake_v0.92.0 plugin crashed!

### ISSUE THREAD

**Issue by liamjamesfoley** [Snowflake-Labs/terraform-provider-snowflake#2874]
### Terraform CLI Version

1.7.1

### Terraform Provider Version

0.92.0

### Terraform Configuration

```terraform
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

Stack trace from the terraform-provider-snowflake_v0.92.0 plugin:

panic: interface conversion: sdk.ObjectIdentifier is sdk.AccountObjectIdentifier, not sdk.SchemaObjectIdentifier

goroutine 82173 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.ReadTask(0xc0020a4980, {0x1cd1dc0?, 0xc000cd24c0?})
    github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/task.go:170 +0xdf8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x2482c98?, {0x2482c98?, 0xc002533530?}, 0xd?, {0x1cd1dc0?, 0xc000cd24c0?})
    github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:783 +0x163
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000b2c2a0, {0x2482c98, 0xc002533530}, 0xc001641ad0, {0x1cd1dc0, 0xc000cd24c0})
    github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:1089 +0x552
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0009af5f0, {0x2482c98?, 0xc0025333b0?}, 0xc000c8c800)
    github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/grpc_provider.go:667 +0x48a
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ReadResource({{0x24999c0?, 0xc0009af5f0?}}, {0x2482c98?, 0xc0025333b0?}, 0xc000c8c680?)
    github.com/hashicorp/terraform-plugin-mux@v0.15.0/tf5to6server/tf5to6server.go:215 +0x225
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ReadResource(0x2482cd0?, {0x2482c98?, 0xc0025330b0?}, 0xc000c8c680)
    github.com/hashicorp/terraform-plugin-mux@v0.15.0/tf6muxserver/mux_server_ReadResource.go:35 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0xc0008cd860, {0x2482c98?, 0xc002709080?}, 0xc000e09d40)
    github.com/hashicorp/terraform-plugin-go@v0.22.2/tfprotov6/tf6server/server.go:776 +0x4c3
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0x2038060?, 0xc0008cd860}, {0x2482c98, 0xc002709080}, 0xc001719580, 0x0)
    github.com/hashicorp/terraform-plugin-go@v0.22.2/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:482 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000ac4600, {0x2482c98, 0xc002708ff0}, {0x2494b60, 0xc000140600}, 0xc0012e1d40, 0xc000b33f50, 0x3443aa8, 0x0)
    google.golang.org/grpc@v1.63.2/server.go:1369 +0xe23
google.golang.org/grpc.(*Server).handleStream(0xc000ac4600, {0x2494b60, 0xc000140600}, 0xc0012e1d40)
    google.golang.org/grpc@v1.63.2/server.go:1780 +0x1016
google.golang.org/grpc.(*Server).serveStreams.func2.1()
    google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 7
    google.golang.org/grpc@v1.63.2/server.go:1030 +0x135

Error: The terraform-provider-snowflake_v0.92.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```
```


### Category

category:resource

### Object type(s)

_No response_

### Expected Behavior

I expect not to get runtime errors during plans.

### Actual Behavior

I got a runtime error during a plan

### Steps to Reproduce

I'm importing 4 Snowflake tasks with this module
```
resource "snowflake_task" "task" {
  comment = var.comment

  database  = var.database
  schema    = var.schema
  warehouse = var.warehouse_name

  name          = var.task_name
  schedule      = var.schedule
  sql_statement = var.sql_statement

  session_parameters = var.session_parameters

  user_task_timeout_ms = var.task_timeout
  after                = var.after
  when                 = var.when
  enabled              = var.enabled

  lifecycle {
    ignore_changes = [enabled]
  }
}

resource "snowflake_grant_ownership" "task_owner_grant" {
  account_role_name = var.task_owner_role
  on {
    object_type = "TASK"
    object_name = "{var.database}.{var.schema}.${snowflake_task.task.name}"
  }
  outbound_privileges = "COPY"
}
```


### How much impact is this issue causing?

Medium

### Logs

_No response_

### Additional Information

_No response_

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-asawicki** [comment]
Hey @liamjamesfoley. Thanks for reaching out to us.

Can you please share the import statement you used to do the import? Did you use the https://registry.terraform.io/providers/Snowflake-Labs/snowflake/0.92.0/docs/resources/task#import syntax (with `|` separation)?

**Comment by liamjamesfoley** [comment]
Hello @sfc-gh-asawicki,

Thanks for the catch. I was using the wrong import syntax, with this commit (screenshot) my change now plans correctly 🎉 

<img width="1359" alt="image" src="https://github.com/Snowflake-Labs/terraform-provider-snowflake/assets/4086743/15101888-bbb2-4b7b-a146-acf6f5f7a922">

**Comment by sfc-gh-asawicki** [comment]
I am closing the issue then! :)
