### ISSUE TITLE
[Bug]: snowflake_database from share throws Go exception

### ISSUE THREAD

**Issue by Bryan-Meier** [Snowflake-Labs/terraform-provider-snowflake#2875]
### Terraform CLI Version

OpenTofu 1.7.0

### Terraform Provider Version

0.88.0 or 0.92.0

### Terraform Configuration

```terraform
resource "snowflake_database" "target_database" {
    name = "ENV_SOME_DATABASE_NAME"
    comment = "Some database comment"

    from_share = {
        share_name = "SOURCE_SHARE_NAME"
        provider = "ACCOUNT_LOCATOR"  # (I have tried this in the ORG.ACCOUNT format and just the Account Locator format and it throws the same error)
    }
    
    provider = snowflake.some_account_provider
}
```

### Category

category:resource

### Object type(s)

resource:database

### Expected Behavior

New database created from the share specified.

### Actual Behavior

After a successful plan an error is thrown on apply:

```
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-snowflake_v0.88.0 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 90 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.CreateDatabase(0x0, {0x1cd4500, 0xc000b14078})
	github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/database.go:114 +0x1046
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x2452b48, {0x2452b48, 0xc000d11a70}, 0xd, {0x1cd4500, 0xc000b14078})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:766 +0x163
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000667ce0, {0x2452b48, 0xc000d11a70}, 0xc0009f7a00, 0xc00082f180, {0x1cd4500, 0xc000b14078})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/resource.go:909 +0xa89
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000a29410, {0x2452b48, 0xc000d118c0}, 0xc000c07ef0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.31.0/helper/schema/grpc_provider.go:1074 +0xdbc
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ApplyResourceChange({{0x24689e0, 0xc000a29410}}, {0x2452b48, 0xc000d118c0}, 0x0)
	github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf5to6server/tf5to6server.go:37 +0x54
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ApplyResourceChange(0x2452b80, {0x2452b48, 0xc000d115c0}, 0xc000c07ea0)
	github.com/hashicorp/terraform-plugin-mux@v0.13.0/tf6muxserver/mux_server_ApplyResourceChange.go:36 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc000a38b40, {0x2452b48, 0xc000d10bd0}, 0xc000b03260)
	github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/tf6server/server.go:857 +0x56b
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x2026fc0, 0xc000a38b40}, {0x2452b48, 0xc000d10bd0}, 0xc00082e600, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:503 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000142d20, {0x2452b48, 0xc000d10b40}, {0x2463c60, 0xc000afa000}, 0xc000d0e7e0, 0xc000ad4f00, 0x345ae58, 0x0)
	google.golang.org/grpc@v1.60.0/server.go:1372 +0xe03
google.golang.org/grpc.(*Server).handleStream(0xc000142d20, {0x2463c60, 0xc000afa000}, 0xc000d0e7e0)
	google.golang.org/grpc@v1.60.0/server.go:1783 +0xfec
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.60.0/server.go:1016 +0x59
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 14
	google.golang.org/grpc@v1.60.0/server.go:1027 +0x115

Error: The terraform-provider-snowflake_v0.88.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Steps to Reproduce

1. Create share in source account
2. Grant usage on database to share using snowflake_grant_privileges_to_share resource
3. Grant usage on schema(s) to share using snowflake_grant_privileges_to_share resource
4. Grant select on tables(s) to share using snowflake_grant_privileges_to_share resource
5. Grant select on views(s) to share using snowflake_grant_privileges_to_share resource
6. Create database in target account from share created in step 1 using snowflake_database resource

### How much impact is this issue causing?

High

### Additional Information

In the target account, when I look at the query history, I can tell that the provider has not attempted to create the database. This tells me the there is a failure in the Go code before it get's to the point of executing SQL statements against the account.

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-asawicki** [comment]
Hey @Bryan-Meier. Thanks for reaching out to us.

The database resource was redesigned deeply and will be released as part of v0.93.0. Please try the new resource out after the release (expected at the end of the next week).

**Comment by sfc-gh-asawicki** [comment]
Also, I believe it should be `share` instead of `share_name` inside the `from_share` block (according to example from https://registry.terraform.io/providers/Snowflake-Labs/snowflake/0.92.0/docs/resources/database#example-usage). Could you try if that helps?

**Comment by Bryan-Meier** [comment]
I'm a bit embarrassed to say that I leaned a little to heavy on GitHub Copilot to generate my initial stub of code and didn't catch that the snowflake_database resource didn't match the documentation. I should have caught that. 😦 

I apologize for the false alarm.
