### ISSUE TITLE
[Bug]: Terraform import snowflake_masking_policy

### ISSUE THREAD

**Issue by SergejKko** [Snowflake-Labs/terraform-provider-snowflake#2888]
### Terraform CLI Version

1.8.0

### Terraform Provider Version

0.92.0

### Terraform Configuration

```terraform
Running the following command:
terraform import -var-file=config.tfvars 'snowflake_masking_policy.mp["<DB.SCHEMA.MP-NAME>"]' '<DB.SCHEMA.MP-NAME>'

And getting the following error message:
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.

│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.

Stack trace from the terraform-provider-snowflake_v0.92.0 plugin:

panic: interface conversion: sdk.ObjectIdentifier is sdk.AccountObjectIdentifier, not sdk.SchemaObjectIdentifier

goroutine 28 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.ReadMaskingPolicy(0x14000146d00, {0x1019962c0?, 0x1400007c938?})
        github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/masking_policy.go:189 +0x6cc
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x101d93818?, {0x101d93818?, 0x14000e29ad0?}, 0xd?, {0x1019962c0?, 0x1400007c938?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:783 +0x134
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x1400066c540, {0x101d93818, 0x14000e29ad0}, 0x14000a87d40, {0x1019962c0, 0x1400007c938})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:1089 +0x430
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x14000bc9980, {0x101d93818?, 0x14000e29980?}, 0x14000932b00)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/grpc_provider.go:667 +0x3e4
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ReadResource({{0x101da9cf8?, 0x14000bc9980?}}, {0x101d93818?, 0x14000e29980?}, 0x14000932940?)
        github.com/hashicorp/terraform-plugin-mux@v0.15.0/tf5to6server/tf5to6server.go:215 +0x228
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ReadResource(0x101d93850?, {0x101d93818?, 0x14000e29680?}, 0x14000932940)
        github.com/hashicorp/terraform-plugin-mux@v0.15.0/tf6muxserver/mux_server_ReadResource.go:35 +0x184
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0x14000bcb400, {0x101d93818?, 0x14000e28c90?}, 0x14000b61620)
        github.com/hashicorp/terraform-plugin-go@v0.22.2/tfprotov6/tf6server/server.go:776 +0x3c4
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0x101cfa580?, 0x14000bcb400}, {0x101d93818, 0x14000e28c90}, 0x14000a3bd80, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.22.2/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:482 +0x164
google.golang.org/grpc.(*Server).processUnaryRPC(0x140008aba00, {0x101d93818, 0x14000e28c00}, {0x101da51c0, 0x140000e8180}, 0x14000f16240, 0x14000aa1cb0, 0x102b9bb08, 0x0)
        google.golang.org/grpc@v1.63.2/server.go:1369 +0xba0
google.golang.org/grpc.(*Server).handleStream(0x140008aba00, {0x101da51c0, 0x140000e8180}, 0x14000f16240)
        google.golang.org/grpc@v1.63.2/server.go:1780 +0xc80
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.63.2/server.go:1019 +0x8c
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 53
        google.golang.org/grpc@v1.63.2/server.go:1030 +0x150

Error: The terraform-provider-snowflake_v0.92.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Category

category:resource

### Expected Behavior

Expecting an existing resource to be imported into terraform state file 

### Actual Behavior

Request was cancelled after import preparation and refresh:

```
snowflake_masking_policy.mp["<DB.SCHEMA.MP-NAME>"]: Importing from ID "<DB.SCHEMA.MP-NAME>"...
snowflake_masking_policy.mp["<DB.SCHEMA.MP-NAME>"]: Import prepared!
  Prepared snowflake_masking_policy for import
snowflake_masking_policy.p["<DB.SCHEMA.MP-NAME>"]: Refreshing state... [id=<DB.SCHEMA.MP-NAME>]
╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
```

### Steps to Reproduce

Prerequisite:
Create any Masking Policy in Snowflake by following official documentation - https://docs.snowflake.com/en/sql-reference/sql/create-masking-policy
And try to import it into terraform state file

1. Create `masking_policies.tf` with the following content:
```
resource "snowflake_masking_policy" "mp" {
  provider = snowflake.sysadmin
  for_each = var.masking_policies
  name     = each.value.name
  database = each.value.database
  schema   = each.value.schema
  signature {
    column {
      name = each.value.signature_column_name
      type = each.value.signature_column_type
    }
  }
  masking_expression = file("${path.module}/masking_policy_bodies/${each.value.masking_expression_location}")
  return_data_type   = each.value.return_data_type
}
```

2. Create `config.tfvars` with the following content:
```
masking_policies = {
  "DB.SCHEMA.MP-NAME" = {
    name                        = "MP-NAME"
    database                    = "DB",
    schema                      = "SCHEMA",
    signature_column_name       = "VAL",
    signature_column_type       = "TIMESTAMP_NTZ",
    masking_expression_location = "MP-NAME.sql"
    return_data_type            = "TIMESTAMP_NTZ"
  }
}
```

3. Create variables.tf with the following content:
```
variable "masking_policies" {
  description = "Masking Policies"
  type        = map(any)
}
```
4. Create main.tf with the following content:
```
terraform {
  required_version = ">=1.8.0"
  required_providers {
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "0.92.0"
    }
  }
```
5. Create providers.tf with the following content:
```
provider "snowflake" {
  alias    = "sysadmin"
  user = var.TFSNOW_USER
  account  = var.ACCOUNT
  password = var.TFSNOW_PASS
  role     = "SYSADMIN"
}
```
6. Try to import previously created masking policy:
`terraform import -var-file=config.tfvars 'snowflake_masking_policy.mp["<DB.SCHEMA.MP-NAME>"]' '<DB.SCHEMA.MP-NAME>'`

### How much impact is this issue causing?

Medium

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-jcieslak** [comment]
Hey @SergejKko 👋 
Could you check if removing `<` and `>` helps? This seems an import command error. The command should look like
```shell
terraform import -var-file=config.tfvars 'snowflake_masking_policy.mp["DB.SCHEMA.MP-NAME"]' 'DB.SCHEMA.MP-NAME'
```

**Comment by SergejKko** [comment]
> Hey @SergejKko 👋 Could you check if removing `<` and `>` helps? This seems to be an import command error. Additionally the separator for identifier should be the pipe character `|` instead of dots. The command should look like
> 
> ```shell
> terraform import -var-file=config.tfvars 'snowflake_masking_policy.mp["DB.SCHEMA.MP-NAME"]' 'DB|SCHEMA|MP-NAME'
> ```
> 
> Every resource has an import section at the bottom of the documentation in the Terraform Registry. Here's a link to the masking policy https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/masking_policy#import.

Thanks!
`|` fixed my problem :) 
Recently I've been importing a lot of procedures where the patterns uses dots (`dbName.schemaName.procedureName(varchar, varchar, varchar)`) instead of pipes :)  Thought the same valid for the masking policies
