### ISSUE TITLE
[Bug]: Error when importing snowflake_network_rule

### ISSUE THREAD

**Issue by lucasmazza** [Snowflake-Labs/terraform-provider-snowflake#2901]
### Terraform CLI Version

1.7.4

### Terraform Provider Version

0.92.0

### Terraform Configuration

```terraform
resource "snowflake_network_rule" "my_rule" {
  name       = "MY_RULE"
  database   = "DB_NAME"
  schema     = "SCHEMA"
  type       = "IPV4"
  mode       = "INGRESS"
  value_list = ["..."]
}
```

### Category

category:resource

### Expected Behavior

I expected to import our `snowflake_network_rule` that is being used by an existing `snowflake_network_policy`

### Actual Behavior

```
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs
│ may contain more details.
╵

╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadDataSource call. The plugin logs
│ may contain more details.
╵

╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadDataSource call. The plugin logs
│ may contain more details.
╵

╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ValidateDataResourceConfig call. The
│ plugin logs may contain more details.
╵


Stack trace from the terraform-provider-snowflake_v0.92.0 plugin:

panic: interface conversion: sdk.ObjectIdentifier is sdk.AccountObjectIdentifier, not sdk.SchemaObjectIdentifier

goroutine 101 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.ReadContextNetworkRule({0x103d2b8c0, 0x14001034690}, 0x1400102c580, {0x10392e2c0?, 0x1400069d0f8?})
	github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/network_rule.go:122 +0x9dc
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x1400068ec40, {0x103d2b818, 0x14001009440}, 0xd?, {0x10392e2c0, 0x1400069d0f8})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:795 +0xe8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x1400068ec40, {0x103d2b818, 0x14001009440}, 0x1400103a270, {0x10392e2c0, 0x1400069d0f8})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:1089 +0x430
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x14000cd1500, {0x103d2b818?, 0x140010092f0?}, 0x14000ca66c0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/grpc_provider.go:667 +0x3e4
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ReadResource({{0x103d41cf8?, 0x14000cd1500?}}, {0x103d2b818?, 0x140010092f0?}, 0x14000ca6540?)
	github.com/hashicorp/terraform-plugin-mux@v0.15.0/tf5to6server/tf5to6server.go:215 +0x228
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ReadResource(0x103d2b850?, {0x103d2b818?, 0x14001008ff0?}, 0x14000ca6540)
	github.com/hashicorp/terraform-plugin-mux@v0.15.0/tf6muxserver/mux_server_ReadResource.go:35 +0x184
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0x14000b04d20, {0x103d2b818?, 0x14001008600?}, 0x14001012180)
	github.com/hashicorp/terraform-plugin-go@v0.22.2/tfprotov6/tf6server/server.go:776 +0x3c4
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0x103c92580?, 0x14000b04d20}, {0x103d2b818, 0x14001008600}, 0x1400102c000, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.22.2/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:482 +0x164
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000df1c00, {0x103d2b818, 0x14001008570}, {0x103d3d1c0, 0x14000142600}, 0x14001014360, 0x140009e3110, 0x104b33b08, 0x0)
	google.golang.org/grpc@v1.63.2/server.go:1369 +0xba0
google.golang.org/grpc.(*Server).handleStream(0x14000df1c00, {0x103d3d1c0, 0x14000142600}, 0x14001014360)
	google.golang.org/grpc@v1.63.2/server.go:1780 +0xc80
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.63.2/server.go:1019 +0x8c
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 16
	google.golang.org/grpc@v1.63.2/server.go:1030 +0x150

Error: The terraform-provider-snowflake_v0.92.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Steps to Reproduce

```
terraform import snowflake_network_rule.my_rule MY_RULE
```

### How much impact is this issue causing?

Low

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-asawicki** [comment]
Hey @lucasmazza. THanks for reaching out to us.

Did you follow the documentation for import https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/network_rule#import? It seems you are not using `|`-separated fully qualified name.

**Comment by lucasmazza** [comment]
@sfc-gh-asawicki I missed that, sorry 🤦

**Comment by sfc-gh-asawicki** [comment]
No problem! Did the import work for you? If so, can we close the issue?
