### ISSUE TITLE
[Bug]: Setting Column Default Crashes Snowflake Plugin

### ISSUE THREAD

**Issue by wpl-sf-nbirch** [Snowflake-Labs/terraform-provider-snowflake#2997]
### Terraform CLI Version

1.9.4

### Terraform Provider Version

0.94.1

### Terraform Configuration

```terraform
Updated a table resource to set the DUPLICATE column to default constant = 0

resource "snowflake_table" "reporting_h" {
  database                    = var.snowflake_database
  schema                      = var.snowflake_schema
  name                        = local.report_h
  comment                     = "h reporting."
  cluster_by                  = []
  change_tracking             = false
  data_retention_time_in_days = 1

  column {
    name     = "KEY"
    type     = "VARCHAR(16777216)"
    nullable = false
  }

  column {
    name = "LOAD_TIMESTAMP"
    type = "TIMESTAMP_NTZ(9)"
  }

  column {
    name = "DUPLICATE"
    type = "NUMBER(38,0)"

    default {
      constant = 0
    }
  }
}
```

### Category

category:resource

### Expected Behavior

Table should be updated to have DUPLICATE column default to 0.

### Actual Behavior

Get a plugin crash with the following errors:

Error: Plugin did not respond
The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.

Error: Request cancelled
The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.

```
Stack trace from the terraform-provider-snowflake_v0.94.1 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15c152c]

goroutine 151 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk.(*TableColumnActionRequest).toOpts(0xc000f0f1f0)
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk/tables_impl.go:368 +0x56c
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk.(*AlterTableRequest).toOpts(0xc000a131d0)
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk/tables_impl.go:128 +0x1a5
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk.(*tables).Alter(0xc0008584f8, {0x24b1240, 0x34cf420}, 0x1?)
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk/tables_impl.go:59 +0x25
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.UpdateTable(0xc0011cec00, {0x1cfa200?, 0xc00006caa0?})
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/table.go:817 +0x1f26
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x24b1278?, {0x24b1278?, 0xc0011df050?}, 0xd?, {0x1cfa200?, 0xc00006caa0?})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:800 +0x163
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000b3d260, {0x24b1278, 0xc0011df050}, 0xc00102bad0, 0xc0011cea80, {0x1cfa200, 0xc00006caa0})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:919 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00062aac8, {0x24b1278?, 0xc0011deea0?}, 0xc001189630)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/grpc_provider.go:1078 +0xdbc
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ApplyResourceChange({{0x24c7fc0?, 0xc00062aac8?}}, {0x24b1278, 0xc0011deea0}, 0x0?)
github.com/hashicorp/terraform-plugin-mux@v0.15.0/tf5to6server/tf5to6server.go:47 +0x54
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ApplyResourceChange(0x24b12b0?, {0x24b1278?, 0xc0011deba0?}, 0xc0011895e0)
github.com/hashicorp/terraform-plugin-mux@v0.15.0/tf6muxserver/mux_server_ApplyResourceChange.go:36 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc0001ff680, {0x24b1278?, 0xc0011de390?}, 0xc00110a460)
github.com/hashicorp/terraform-plugin-go@v0.22.2/tfprotov6/tf6server/server.go:846 +0x3d0
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x20639e0?, 0xc0001ff680}, {0x24b1278, 0xc0011de390}, 0xc0011ce580, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.22.2/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:518 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0009dee00, {0x24b1278, 0xc0011de300}, {0x24c31e0, 0xc000016300}, 0xc0011a1e60, 0xc000bdc570, 0x348ad38, 0x0)
google.golang.org/grpc@v1.63.2/server.go:1369 +0xe23
google.golang.org/grpc.(*Server).handleStream(0xc0009dee00, {0x24c31e0, 0xc000016300}, 0xc0011a1e60)
google.golang.org/grpc@v1.63.2/server.go:1780 +0x1016
google.golang.org/grpc.(*Server).serveStreams.func2.1()
google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 14
google.golang.org/grpc@v1.63.2/server.go:1030 +0x135

Error: The terraform-provider-snowflake_v0.94.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Steps to Reproduce

1. Create a table resource with a default
2. Update the table resource with a default constant

### How much impact is this issue causing?

Low

### Additional Information

Seems similar to [2406](https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/2406)

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by sfc-gh-jmichalak** [comment]
Hi @wpl-sf-nbirch 👋 Thanks for reporting this issue. We will rework this resource as stated in our [roadmap](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/ROADMAP.md#preparing-essential-ga-objects-for-the-provider-v1).

**Comment by pdreker** [comment]
As this is slated for a rework, I will just chime in, instead of opening a new issue, as it seems related:
When declaring a table with a column with a "NOT NULL" constraint and a default of `""` the provider seems to not use the empty string as a default, due to the code in `pgk/resources/table.go`, L317 and following. In line 319 the code checks, if the passed in constant is longer than 0, which the empty string isn't and as such the code falls through and internally returns `nil` for the default, which runs afoul of the "NOT NULL" constraint and causing the provider to crash futher along the way very similar to what was reported here earlier.

**Comment by mattmie** [comment]
I believe I am getting a similar error in 2.1.0 so I thought I would provide that stack trace. Is there a planned roadmap item for this bug?

`Stack trace from the terraform-provider-snowflake_v2.1.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x101f149dc]

goroutine 73 [running]:
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk.(*TableColumnActionRequest).toOpts(0x14000b2fab0)
        github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk/tables_impl.go:376 +0x51c
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk.(*AlterTableRequest).toOpts(0x140010531d0)
        github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk/tables_impl.go:136 +0x198
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk.(*tables).Alter(0x1400020f518, {0x102f5bac8, 0x14000c59980}, 0x1?)
        github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/sdk/tables_impl.go:59 +0x2c
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.UpdateTable({0x102f5bac8, 0x14000c59980}, 0x14000fa3480, {0x102af43c0, 0x1400079ff00})
        github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/table.go:851 +0x1ccc
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.Table.TrackingUpdateWrapper.func7({0x102f5bb70, 0x14000b2f260}, 0x14000fa3480, {0x102af43c0, 0x1400079ff00})
        github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/common.go:146 +0xf0
github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources.Table.PreviewFeatureUpdateContextWrapper.func8({0x102f5bb70, 0x14000b2f260}, 0x14000fa3480, {0x102af43c0, 0x1400079ff00})
        github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources/common.go:199 +0x84
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x14000939000, {0x102f5bac8, 0x14000357170}, 0x14000fa3480, {0x102af43c0, 0x1400079ff00})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.36.1/helper/schema/resource.go:872 +0xe4
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x14000939000, {0x102f5bac8, 0x14000357170}, 0x14001206d00, 0x14000fa3300, {0x102af43c0, 0x1400079ff00})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.36.1/helper/schema/resource.go:979 +0x660
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x140006980f0, {0x102f5bac8?, 0x14000356ff0?}, 0x140011a8910)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.36.1/helper/schema/grpc_provider.go:1188 +0xaa4
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ApplyResourceChange({{0x102f89c40?, 0x140006980f0?}}, {0x102f5bac8, 0x14000356ff0}, 0x0?)
        github.com/hashicorp/terraform-plugin-mux@v0.18.0/tf5to6server/tf5to6server.go:38 +0x58
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ApplyResourceChange(0x140007a7700, {0x102f5bac8?, 0x14000ab9f50?}, 0x140011a88c0)
        github.com/hashicorp/terraform-plugin-mux@v0.18.0/tf6muxserver/mux_server_ApplyResourceChange.go:36 +0x184
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0x140004a1180, {0x102f5bac8?, 0x14000ab94d0?}, 0x14000b2e2a0)
        github.com/hashicorp/terraform-plugin-go@v0.26.0/tfprotov6/tf6server/server.go:866 +0x2a8
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x102ed3f80, 0x140004a1180}, {0x102f5bac8, 0x14000ab94d0}, 0x14000fa2800, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.26.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:611 +0x1c0
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000a37a00, {0x102f5bac8, 0x14000ab9440}, 0x140003261e0, 0x14000a4d470, 0x103f7ded8, 0x0)
        google.golang.org/grpc@v1.71.1/server.go:1405 +0xca8
google.golang.org/grpc.(*Server).handleStream(0x14000a37a00, {0x102f5f368, 0x14000942340}, 0x140003261e0)
        google.golang.org/grpc@v1.71.1/server.go:1815 +0x910
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.71.1/server.go:1035 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 16
        google.golang.org/grpc@v1.71.1/server.go:1046 +0x13c

Error: The terraform-provider-snowflake_v2.1.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.`

**Comment by sfc-gh-jmichalak** [comment]
Hi @mattmie 👋 

Similarly to other issues, this will be fixed during a table rework. Currently, we don't have a timeline for it.

**Comment by olysyuk** [comment]
Still reproducible in version v2.3.0

This line expects `identity` property when `constant` is used.
https://github.com/snowflakedb/terraform-provider-snowflake/blob/main/pkg/sdk/tables_impl.go#L373

**Comment by jasonjoneszywave** [comment]
Also running into this issue with v2.3.0. Mine is similar to the origjnal poster's setting a default on a boolean column causes the plugin error. Posting in the hopes that more voices will boost the priority for getting the table rework in the queue and this bug resolved.

**Comment by juliankeppel** [comment]
Still same behavior in version 2.15.0. Exact the same situation as in the original post.

Are there any workarounds besides altering the table manually? I will set the column nullable now, this is somehow acceptable in my situation.

**Comment by sfc-gh-jmichalak** [comment]
Hi all, as I stated above, this resource is still in preview, and these issues will be addressed during rework (no timelines yet). If you would like to bump the priority, please report this request through your Snowflake Account Executive. This helps us prioritize and deliver faster. 

The current workaround is to alter the table manually, e.g. with the [execute](https://registry.terraform.io/providers/snowflakedb/snowflake/latest/docs/resources/execute) resource.

**Comment by MyJBMe** [comment]
Still same behavior in version 2.17.0. Will report this request through SAE.

**Comment by sfc-gh-jmichalak** [comment]
Hi All 👋 

We've just released v2.18.0 ([release notes](https://github.com/snowflakedb/terraform-provider-snowflake/releases/tag/v2.18.0), [migration guide](https://github.com/snowflakedb/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md#v217x--v2180)). This version fixes this panic. Enjoy!

**Comment by sfc-gh-jmichalak** [comment]
Closing due to inactivity.
